お届け先選択で「会員の住所」を選択できるようにする
EC-CUBE/ec-cube pull request #3174
Opened 2018-06-14 08:23 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

- 現状(3.0)
  - 注文時は、お届け先のリストからのみ、お届け先を選択できる。
  - マイページで会員情報を変更した場合、「会員住所」と「お届け先リストの住所」が異なる状態になる。

- やりたいこと
  - 注文時に、「会員住所」＆「お届け先リストの住所」からお届け先を選択できる。
  - お届け先のデフォルトは「会員住所」となる。

# 方針

- 注文時に、「会員住所」＆「お届け先リストの住所」からお届け先を選択できる
- お届け先のデフォルトは「会員住所」となる。
- 会員登録時にお届け先リストには追加しない

## テスト（Test)
- travis-ciがパスすることを確認

2018-06-18 03:01 UTC, nanasess approved these changes
ゲスト購入時、お届け先の変更で入力した内容が、お届け先の複数指定のリストに反映されないという問題がありますが、それ以外は問題なさそうです。

2018-06-18 05:36 UTC, okazy requested changes
フロント画面からの会員登録は問題ありませんでしたが、管理画面からとコマンドでの会員作成でも変更が必要かと思います。
- [x] フロント画面会員登録
- [x] 管理画面会員登録
- [x] `bin/console e:f:g` での会員追加

2018-06-19 04:30 UTC, okazy approved these changes

2018-06-19 04:31 UTC, okazy commented
以下追加で修正しました。
- [x] 管理画面会員登録
- [x] `bin/console e:f:g` での会員追加

codeceptionの修正もしていますので、ドキュメントも合わせて取り込みをお願いいたします。
https://github.com/EC-CUBE/eccube3-doc/pull/28

2018-06-19 06:52 UTC, kiy0taka commented on src/Eccube/Form/Type/ShippingMultipleItemType.php
> +                    'choice_label' => function ($Address) {
`$Address->getShippingMultipleDefaultName()`を返すだけなので、callableにする必要はないですね。

2018-06-19 07:08 UTC, kiy0taka requested changes

2018-06-19 07:08 UTC, kiy0taka commented on src/Eccube/Form/Type/ShippingMultipleItemType.php
> +                    'choice_label' => function ($Address) {
`choice_label `は`'shippingMultipleDefaultName'`でいいと思います。

2018-06-19 07:33 UTC, kiy0taka approved these changes

2018-06-19 07:56 UTC, chihiro-adachi commented
@okazy テスト仕様書、マージしています。

2018-06-19 08:29 UTC, merged