PaymentMethod, PaymentService をコンテナから取得するよう修正
EC-CUBE/ec-cube pull request #3240
Opened 2018-06-28 05:52 UTC by nanasess

## 概要(Overview・Refs Issue)
+ PaymentMethod, PaymentService をコンテナから取得するよう修正

## 方針(Policy)
+ CompilerPass クラスを作成し、 PaymentMethod, PaymentService を Autowiring の対象とする

## 実装に関する補足(Appendix)
+ メソッドコメントを追記
+ 暫定実装だった個所の修正

## テスト（Test)
+ ユニットテストの通ることを確認

2018-06-28 08:49 UTC, chihiro-adachi requested changes

2018-06-28 08:49 UTC, chihiro-adachi commented on src/Eccube/DependencyInjection/Compiler/PaymentMethodPass.php
> +            $def->setPublic(true);
is_subclass_ofのチェックのあとでsetPublic(true)をおねがいします。

2018-06-28 08:49 UTC, chihiro-adachi commented on src/Eccube/DependencyInjection/Compiler/PaymentMethodPass.php
> +            $container->setParameter($class, $class);
不要な処理と思われるので、削除をおねがいします。

2018-06-28 09:12 UTC, nanasess commented on src/Eccube/DependencyInjection/Compiler/PaymentMethodPass.php
> +            $def->setPublic(true);
対応しました

2018-06-28 09:12 UTC, nanasess commented on src/Eccube/DependencyInjection/Compiler/PaymentMethodPass.php
> +            $container->setParameter($class, $class);
対応しました

2018-06-29 00:15 UTC, chihiro-adachi approved these changes

2018-07-01 23:45 UTC, chihiro-adachi requested changes

2018-07-01 23:45 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +                $Payment->setMethodClass(Cash::class); // Payment method class of Cash to default.
@nanasess 
プラグイン等から支払い方法を追加した場合に上書きされてしまうため、修正をお願いします。

2018-07-02 00:40 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +                $Payment->setMethodClass(Cash::class); // Payment method class of Cash to default.
更新時に上書きしないようにしてみました

2018-07-02 00:53 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +                $Payment->setMethodClass(Cash::class); // Payment method class of Cash to default.
ありがとうございます！

2018-07-02 03:33 UTC, chihiro-adachi approved these changes

2018-07-02 04:43 UTC, kiy0taka approved these changes

2018-07-02 07:34 UTC, merged