#64 【レイアウト管理】登録時にエラーが発生した場合に変更内容が失われてしまう。
EC-CUBE/ec-cube pull request #3364
Opened 2018-07-19 06:44 UTC by KenTanaka

## 概要(Overview・Refs Issue)
+ 新規、修正ともに、ページ名空白などの状態で登録・更新アクションを実施すると、並べていたレイアウト情報が初期化されてしまう。

## 方針(Policy)
+ リクエストされた情報からレイアウト情報の復元を行う処理が入っていなかった為、処理を追加

## 実装に関する補足(Appendix)
+  Eccube\Entity\Layout\getBlockPositionsByでフィルター後のArrayCollectionをblock_rowの昇順でソートするようにしています。
 - 例えば、headerセクションに A/B ブロックを配置して登録後、B/Aブロックの順に変更した状態でエラーが発生（名称空白）した場合に、A/Bに戻ってしまう現象が発生した為、その対処としてblock_row順で返すようにする対処の為となります。

## テスト（Test)
+ 1) ページ新規登録時　名前空白で ブロック配置し、エラー発生後も維持されている事
+ 2) ページ修正時 登録済みページを表示し、名前空白で 新規ブロック追加、既存ブロック移動・既存ブロック同ブロック内で並べ替えなど実行し、エラー発生後も維持されている事

## 相談（Discussion）
+ ざっとコーディングしていますが、Symfony（とCUBE新バージョン）の流儀にあっているかどうかがわからない為、改修分は全体的にレビューをお願いします。

2018-07-20 05:38 UTC, ryo-endo commented
動作は良さそうです。
詳細に実装方針書いていただけていますので、開発チームでのレビューお願いします。

2018-08-03 02:36 UTC, kiy0taka commented
復元処理が正常に保存するときと重複しているコードがあるので、共通化できないでしょうか？
LayoutとBlockPositionを組み立てる処理は同じで、エラーの有無で永続化をするかしないかという形になるといいかと思います。`$UnusedBlocks` の処理はエラーの場合に必要になると思います。

2018-08-03 02:36 UTC, kiy0taka requested changes
配置済みのブロックを未使用に変えてからエラーが発生すると、配置済みに戻ってしまいます。

2018-08-03 02:46 UTC, KenTanaka commented
確認・修正します。
コードの構造化については承知しました。

2018-08-13 01:06 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Content/LayoutController.php
> +            $Layout = $this->layoutRepository->findById($id);
`NoResultException`をキャッチして`NotFoundHttpException`をスローするようにお願いします。

2018-08-13 01:27 UTC, kiy0taka requested changes

2018-08-13 01:27 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Content/LayoutController.php
> +            $Layout = $this->layoutRepository->findById($id);
`NoResultException`をキャッチして`NotFoundHttpException`をスローするようにお願いします。

2018-08-14 00:27 UTC, kiy0taka requested changes

2018-08-14 00:27 UTC, kiy0taka commented on src/Eccube/Repository/BlockRepository.php
> +     * @return Block
Scrutinizerの方で指摘されてるのは、このDocコメントの戻り値を`Block[]`にしてもらえれば直ると思います。

2018-11-21 00:50 UTC, yuyu777 commented
こちらで作業を引き取らせていただいた上で、取り込ませていただきます。

2019-03-29 02:15 UTC, chihiro-adachi commented
#4121 で対応しました。

2019-03-29 02:15 UTC, closed without merging