Proxy クラスを利用すると、 Windows 環境で動作しない不具合の対応
EC-CUBE/ec-cube pull request #3412
Opened 2018-07-27 08:41 UTC by nanasess

## 概要(Overview・Refs Issue)
プラグインなどから Entity クラスを拡張する方法として、 [https://github.com/EC-CUBE/ec-cube/pull/2267](Proxy クラスを生成する)方法があるが、 Windows 環境では、クラスの多重定義エラーとなってしまう。

以下の require_once をコメントアウトすれば回避できるが、 アノテーションをロードできなくなってしまう。
https://github.com/EC-CUBE/ec-cube/blob/1999421f5e1b46241a27fadf6130377abc2d114a/src/Eccube/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php#L74-L80

## 方針(Policy)
+ 本体側の Entity クラスに `if (!class_exists('\Eccube\Entity\ClassName)) { 〜 `を入れて多重定義しないようにする
+ Master クラスは Entity拡張で使用しないと思われるため除外

## 実装に関する補足(Appendix)
+ Eccube\Kernel::loadEntityProxies() は PSR-4 Autoloader に定義済みのため削除

## テスト（Test)
+ 既存のテストが通るのを確認

## 相談（Discussion）
+ 本来は AnnotationDriver に class_exists の判定を入れてやるとスマートだが、 PHPファイルを parse してクラス名判定するのを自力でやらなくてはならない感じ...

2018-07-30 00:30 UTC, chihiro-adachi commented
@nanasess 

https://github.com/chihiro-adachi/ec-cube/commit/317bf9e9f0b8e48f4aae42d30c520b6242fdf927

こちらのプラグインをコマンドからインストールしようとすると以下のエラーが発生しました。

```
chihiro_adachi:~/repos/ec-cube-sf (nanasess-fix-classloader $=) $ bin/console e:p:i --code=Sample3
gen -> /var/folders/0t/8f6twlts0vd5qyh4qp3rw6gh391rvb/T/proxy_MPgSjQKgviMA/Customer.php

In MappingException.php line 93:
                                                             
  Class 'Eccube\Entity\CustomerLsQHyBO0XO5h' does not exist  
                                                             
```

環境は以下のとおりです。

- Mac
- PHP 7.2.2
- MySQL 5.6

2018-07-30 02:06 UTC, nanasess commented
@chihiro-adachi こちらの Mac の環境では、全く問題なくインストールできました。もう少し詳しく状況わかりませんか？

2018-07-30 02:16 UTC, nanasess commented
@chihiro-adachi Windows 環境でも全く問題なくインストールできました

2018-07-30 04:09 UTC, chihiro-adachi commented
@nanasess 

手順としてはこんな感じです。インストール後初期状態でプラグインインストールしています。

```
git clone https://github.com/chihiro-adachi/ec-cube.git
cd ec-cube/
git checkout -b nanasess-fix-classloader origin/nanasess-fix-classloader
composer install --dev
bin/console e:i
bin/console e:p:i --code=Sample3

gen -> /var/folders/0t/8f6twlts0vd5qyh4qp3rw6gh391rvb/T/proxy_933Al5uLMHqF/Customer.php

In MappingException.php line 93:
                                                             
  Class 'Eccube\Entity\CustomervFOYazLvBuUM' does not exist  
                                                             
```

2018-07-30 05:10 UTC, nanasess commented
@chihiro-adachi 再現しました。古い proxy が悪さしてたみたいです。 proxy 側の class_exists は削除しないといけなかったですね

2018-07-31 01:16 UTC, chihiro-adachi commented
@nanasess 

以下のようになりました。

```
bin/console e:i
bin/console e:p:i --code=Sample3
bin/console e:p:e --code=Sample3
bin/console e:p:d --code=Sample3

bin/console e:p:i --code=Sample3


chihiro_adachi:~/repos/ec-cube-sf (nanasess-fix-classloader *$=) $ bin/console e:p:d --code=Sample3
PHP Fatal error:  Cannot declare class Eccube\Entity\Customer, because the name is already in use in /Users/chihiro_adachi/repos/ec-cube-sf/app/proxy/entity/Customer.php on line 31

In Customer.php line 31:
                                                                                                  
  Compile Error: Cannot declare class Eccube\Entity\Customer, because the name is already in use  
                                                                                                  
```

2018-07-31 04:59 UTC, chihiro-adachi commented
@nanasess 
Webからのインストールで変な挙動になりました。

- EC-CUBEをインストール
- プラグインをWebからアップロード
  - 「プラグインがインストールできませんでした」のエラーが表示される
- 再度アップロード
  - インストール成功
- 有効にする
  - Cannot declare class Eccube\Entity\BaseInfo

※アップロードをおこなったプラグインはこちらです
https://github.com/EC-CUBE/ec-cube/commit/a2e56f87fdbd1ce10dd374d1470d2945c80678d3

2018-07-31 05:08 UTC, nanasess commented
@chihiro-adachi 該当のプラグインのインストールを試したところ、

> An exception occurred while executing 'ALTER TABLE dtb_customer ADD sample2 VARCHAR(255) NOT NULL':
> SQLSTATE[23502]: Not null violation: 7 ERROR:  column "sample2" contains null values

ということでしたので、 nullable=true にしてあげたらインストールできるかなと

2018-07-31 05:59 UTC, chihiro-adachi commented
@nanasess 
nullable=trueでも同様の事象になりました。
[Sample2.tar.gz](https://github.com/EC-CUBE/ec-cube/files/2243935/Sample2.tar.gz)

ただ、有効化エラー後にvar/cacheを削除すると、以降は問題なく動作します。

2018-07-31 09:27 UTC, nanasess commented
@chihiro-adachi `CacheUtil::cacheClear()` をコメントアウトすると正常に動作するようです。

```diff
diff --git a/src/Eccube/Controller/Admin/Store/PluginController.php b/src/Eccube/Controller/Admin/Store/PluginController.php
index 9f266f283..7b8f92396 100644
--- a/src/Eccube/Controller/Admin/Store/PluginController.php
+++ b/src/Eccube/Controller/Admin/Store/PluginController.php
@@ -271,7 +271,7 @@ class PluginController extends AbstractController
         // キャッシュを削除してリダイレクト
         // リダイレクトにredirectToRoute関数を使用していないのは、削除したキャッシュが再生成されてしまうため。
         $url = $this->generateUrl('admin_store_plugin');
-        $cacheUtil->clearCache();
+        // $cacheUtil->clearCache();

         return $this->redirect($url);
     }
```

別途キャッシュクリアするのは問題ないようなので、何か良い方法はないでしょうか。。。

2018-07-31 10:52 UTC, kiy0taka commented
`$cacheUtil->clearCache()`を呼んでも`terminate`後にキャッシュを消すようにしてみましたが、どうでしょうか？
https://github.com/kiy0taka/ec-cube/commit/e4c21cf37add81ef5a8bd39aef387182b85380ed

2018-08-03 07:51 UTC, nanasess commented
https://github.com/EC-CUBE/ec-cube/pull/3412#issuecomment-409104511 にあるプラグインのサンプルは不具合がありますので、こちらで検証するようお願いします。

[Sample2.tar.gz](https://github.com/EC-CUBE/ec-cube/files/2256498/Sample2.tar.gz)

2018-08-03 08:45 UTC, okazy requested changes
以下のEntityにもclass_existを追加する必要がかとおもいます。

- BlockPosition
- Cart
- CartItem
- Category

2018-08-03 08:45 UTC, okazy commented on src/Eccube/Service/EntityProxyService.php
> +     * @params Tokens $entityTokens
`@params` -> `@param`

2018-08-03 08:57 UTC, nanasess commented
@okazy 修正しました

2018-08-03 09:17 UTC, okazy approved these changes

2018-08-03 11:26 UTC, merged

2018-08-07 11:17 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +        $this->BaseInfo = $baseInfoRepository->get();
@nanasess 
APP_ENV=devの場合、コンテナのコンパイルのタイミングでコンストラクタが呼び出されます。
※このクラスではなく、DoctrineのサブスクライバやTwigのエクステンションのクラスだったかもしれません。

なので、上記コードのようにコンストラクタ内でメソッド呼び出しすると、コンパイルのタイミングでBaseInfoやBaseInfoレポジトリがインスタンス化されます(BaseInfoをインジェクションするのと同じ)

エンティティにclass_existしないとだめだったのは、コンストラクタ内でbaseInfoRepository->get()してたからかなあ、と推測しています。

現状きちんと動いているようなので修正する必要はないとは思いますが、共有まで。