eccube:fixtures:generateコマンドで、--products=0でも動作するように修正。
EC-CUBE/ec-cube pull request #3739
Opened 2018-09-03 07:09 UTC by ryo-endo

## 概要(Overview・Refs Issue)
eccube:fixtures:generateコマンドで、--products=0だとエラーになっていたのを修正。

## 方針(Policy)

なし

## 実装に関する補足(Appendix)

なし

## テスト（Test)

--products=0でも動作することを確認しました。

## 相談（Discussion）

なし

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

2018-09-03 09:01 UTC, kiy0taka requested changes

2018-09-03 09:01 UTC, kiy0taka commented on src/Eccube/Command/GenerateDummyDataCommand.php
> +        $Products = $this->productRepository->findAll();
`findAll()`はいただけない。

2018-09-03 09:34 UTC, nanasess commented on src/Eccube/Command/GenerateDummyDataCommand.php
> +        $Products = $this->productRepository->findAll();
これでどうでしょう？
https://github.com/ryo-endo/ec-cube/pull/9

2018-09-04 09:33 UTC, ryo-endo commented on src/Eccube/Command/GenerateDummyDataCommand.php
> +        $Products = $this->productRepository->findAll();
@nanasess ありがとうございます！

2018-11-21 00:58 UTC, kiy0taka approved these changes

2018-12-03 06:26 UTC, merged