feat テンプレートのアップロード対策に、アップロード最大ファイルサイズを5Mに変更
EC-CUBE/ec-cube pull request #3851
Opened 2018-09-14 06:25 UTC by okazy

## 概要(Overview・Refs Issue)
テンプレートのサイズが2M以上となることがある。（デフォルトのテンプレートが2.2M）
アップロード最大ファイルサイズを5Mに変更した。

## 方針(Policy)
2系では5Mの設定となっていたので合わせています。

## 実装に関する補足(Appendix)
upload_max_filesizeはディレクトリ単位での設定しかできないので.htaccessで設定

## テスト（Test)
apacheでupload_max_filesizeが書き換わることを確認

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

2018-09-20 03:53 UTC, nanasess requested changes

2018-09-20 03:53 UTC, nanasess commented on .htaccess
> +# デフォルトテンプレートの状態で 2M 以上となるため
最近は mod_php ではなく、 fastcgi を使用しているサーバーも多いため、 `IfModule` で囲っておいた方がよいと思います
```
<IfModule mod_php7.c>
    php_value upload_max_filesize 5M
</IfModule>
```

2018-11-20 05:58 UTC, chihiro-adachi commented on .htaccess
> +# デフォルトテンプレートの状態で 2M 以上となるため
@nanasess こちら修正しています。

2018-11-20 12:06 UTC, nanasess approved these changes

2018-11-21 10:48 UTC, merged