インストール時の初期データを言語毎に
EC-CUBE/ec-cube pull request #3868
Opened 2018-09-20 07:00 UTC by tao-s

## 概要(Overview・Refs Issue)
inport csvのディレクトリ分けた

2018-10-23 02:23 UTC, nanasess requested changes

2018-10-23 02:23 UTC, nanasess commented on src/Eccube/Resource/doctrine/import_csv/en/dtb_class_category.csv
> +1,1,,Chololate,Chololate,3,2017-03-07 10:14:52,2017-03-07 10:14:52,1,classcategory
正しくは Chocolate だと思います

2018-10-23 08:31 UTC, tao-s commented on src/Eccube/Resource/doctrine/import_csv/en/dtb_class_category.csv
> +1,1,,Chololate,Chololate,3,2017-03-07 10:14:52,2017-03-07 10:14:52,1,classcategory
おおう...

2018-10-23 09:06 UTC, nanasess approved these changes

2018-11-20 07:08 UTC, chihiro-adachi commented
#3922 をこちらのPRにマージし、 4.0のブランチの最新に追随しています。

2018-11-22 03:00 UTC, okazy approved these changes
動作確認をして問題ありませんでした。

2018-11-22 03:01 UTC, merged