プラグインのマイグレーション機能
EC-CUBE/ec-cube pull request #3960
Opened 2018-11-01 02:41 UTC by nanasess

## 概要(Overview・Refs Issue)
プラグインごとのマイグレーション機能の実装

PluginManager 実行時に、 Doctrine SchemaUpdate が自動的に行なわれるため、この機能は主にデータの更新に使用する.

## 方針(Policy)

- 基本的に3系と同様の実装
   - 4.0 の実態に合わせて引数を変更
- namespace は `\Plugin\<PluginCode>\DoctrineMigrations` とする

## 実装に関する補足(Appendix)
 - マイグレーションファイルの namespace は、クラスのオートローディングから除外することが推奨されているが、 `\Plugin` 以下がすべて PSR-4 Autoload の対象となっているため、除外することが難しい
    - Symfony DI の Autowire からは除外している

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

2018-11-02 10:29 UTC, okazy requested changes
ソースコードと動作確認して問題ありませんでした。
composer.jsonの記述が間違っており、api経由でのインストールに失敗してしまいましすので修正をお願いいたします。

2018-11-02 10:29 UTC, okazy commented on app/Plugin/MigrationSample/composer.json
> +  "name": "Eccube/MigrationSample",
```suggestion
  "name": "ec-cube/MigrationSample",
```

2018-11-05 00:37 UTC, nanasess commented
@okazy 修正しました

2018-11-05 06:26 UTC, okazy approved these changes

2018-11-05 06:28 UTC, merged