インストール済プラグインをcomposer requireするコマンドを追加
EC-CUBE/ec-cube pull request #3997
Opened 2018-11-19 04:05 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

インストール済プラグインをcomposer requireするコマンドを追加

## 方針(Policy)

- 4.0.xのバージョンアップ手順は当初は3.0.xと同等のものを提供する見込み
  - http://doc.ec-cube.net/quickstart_update
- composer.json/lockファイルが、プラグインインストール時に書き換えられるため、インストール済プラグインを再度composer requireし、composer.json/lockファイルを更新する

## 実装に関する補足(Appendix)

以下で実行することができます。

```
bin/console eccube:composer:require-already-installed
```

プラグインがEC-CUBEのバージョンに対応していない場合、以下のダイアログを表示します。
```
Sample Plugin 1.0.0 は EC-CUBE 4.0.1 には対応していません。続行しますか？ (yes/no) [yes]:
```
## テスト（Test)
以下のパターンを動作確認しています。

- プラグインをインストール
- composer.json/lockを上書き
- コマンドを実行
- composer.json/lockにプラグインのrequireが追加されていることを確認

## 相談（Discussion）
+ 相談したいことや意見を求めたいこと

## マイナーバージョン互換性保持のための制限事項チェックリスト
+ マイナーバージョンでは、機能・プラグイン・デザインテンプレート互換性を損なう変更は原則取り込みません。

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

2018-11-19 11:14 UTC, okazy requested changes
動作確認しました。

1. タイポがありましたので修正をお願いします。

2. プラグインインストール後とコマンド実行後でcomposer.jsonのバージョンの指定が異なりました。

プラグインインストール後
```
        "ec-cube/ProductReview4": "^4.0",
```

コマンド実行後
```
        "ec-cube/ProductReview4": "4.0.0",
```

こちら合わせないでも問題ないでしょうか？


その他については問題ありませんでした。

2018-11-19 11:14 UTC, okazy commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        $notSupportedPluigns = [];
```suggestion
        $notSupportedPlugins = [];
```

2018-11-19 11:14 UTC, okazy commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +                $notSupportedPluigns[] = $Plugin;
```suggestion
                $notSupportedPlugins[] = $Plugin;
```

2018-11-19 11:14 UTC, okazy commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        foreach ($notSupportedPluigns as $Plugin) {
```suggestion
        foreach ($notSupportedPlugins as $Plugin) {
```

2018-11-20 02:09 UTC, kiy0taka commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        $Plugins = $this->pluginRepository->findAll();
`$Plugins = $this->pluginRepository->findAll();` だと独自インストールしたプラグインも対象になってしまうと思います。

2018-11-20 02:10 UTC, chihiro-adachi commented
> タイポがありましたので修正をお願いします。

修正しました。

> プラグインインストール後とコマンド実行後でcomposer.jsonのバージョンの指定が異なりました。

プラグインインストール時には、プラグインのバージョン情報は取得していないため、指定が異なるようです。
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Controller/Admin/Store/OwnerStoreController.php#L273

ただ、現状ではバージョンを指定してインストールや更新する仕様はないため、動作上は問題ありません。

2018-11-20 02:11 UTC, kiy0taka requested changes

2018-11-20 02:11 UTC, kiy0taka commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        $Plugins = $this->pluginRepository->findAll();
`$Plugins = $this->pluginRepository->findAll();` だと独自インストールしたプラグインも対象になると思います。

2018-11-20 02:28 UTC, chihiro-adachi commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        $Plugins = $this->pluginRepository->findAll();
@kiy0taka 
独自プラグインとオーナーズストアプラグインの差異は、dtb_plugin.sourceで判別すればよいでしょうか？

2018-11-20 02:30 UTC, kiy0taka commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        $Plugins = $this->pluginRepository->findAll();
それであってると思います。

2018-11-20 02:38 UTC, chihiro-adachi commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +        $Plugins = $this->pluginRepository->findAll();
ありがとうございます。

2018-11-20 03:52 UTC, chihiro-adachi commented
@okazy @kiy0taka 
指摘事項を修正、またはコメント書きましたのでご確認ください

2018-11-20 04:11 UTC, kiy0taka requested changes

2018-11-20 04:11 UTC, kiy0taka commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +            ->where(Criteria::expr()->neq('source', null))
独自インストールのものは`null`ではなく、`0`が入ってるようです。

2018-11-20 05:02 UTC, chihiro-adachi commented on src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
> +            ->where(Criteria::expr()->neq('source', null))
なんと、修正します。

2018-11-20 07:02 UTC, okazy approved these changes

2018-11-20 07:18 UTC, kiy0taka approved these changes

2018-11-22 01:08 UTC, okazy approved these changes
動作確認して問題ありませんでした。
- プラグインのインストール/有効化/無効化/削除
- composer requireコマンド

2018-11-22 01:08 UTC, merged