【WIP】メンテナンス管理から.maintenanceファイルが作成/削除できる
EC-CUBE/ec-cube pull request #4000
Opened 2018-11-19 09:44 UTC by kanako-kina

以下を参考にコメントを作成してください。

## 概要(Overview・Refs Issue)
+ コンテンツ管理にメンテナンス管理メニューを追加し、画面から.maintenanceファイルの作成と削除が行えるようにする

## テスト（Test)
+ メンテナンス管理メニューで、ファイルが作成・削除されることを確認

## マイナーバージョン互換性保持のための制限事項チェックリスト
+ マイナーバージョンでは、機能・プラグイン・デザインテンプレート互換性を損なう変更は原則取り込みません。

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

2018-11-20 01:35 UTC, chihiro-adachi requested changes

2018-11-20 01:35 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Content/MaintenanceController.php
> +            $this->addSuccess(($isMaintenace) ? 'admin.content.maintenance_switch__on_message' : 'admin.content.maintenance_switch__off_message', 'admin');
更新処理完了後はリダイレクトして戻ってくるようにしてください

2018-11-20 01:36 UTC, chihiro-adachi requested changes

2018-11-20 01:36 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.content.maintenance_switch__on: 有効
ボタンの文言が、現在のステータスなのかアクションなのかが分かりづらいので、`有効にする`などの文言のほうが良いかと思います。

2018-11-20 04:24 UTC, nanasess requested changes

2018-11-20 04:24 UTC, nanasess commented on src/Eccube/Controller/Admin/Store/PluginController.php
> +        die();
消し忘れでしょうか？

2018-11-20 05:43 UTC, okazy requested changes

2018-11-20 05:43 UTC, okazy commented on src/Eccube/Controller/Admin/Content/MaintenanceController.php
> +     * @Template("@admin/Content/maintenance.twig")*
```suggestion
     * @Template("@admin/Content/maintenance.twig")
```

2018-11-20 05:43 UTC, okazy commented on src/Eccube/Resource/template/admin/Content/maintenance.twig
> +{% block stylesheet %}
stylesheetのブロックは不要かと思います。

2018-11-20 12:05 UTC, nanasess approved these changes

2018-11-20 12:06 UTC, okazy approved these changes

2018-11-20 12:09 UTC, chihiro-adachi requested changes

2018-11-20 12:09 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Content/MaintenanceController.php
> +            $this->redirectToRoute('admin_content_maintenance');
😢 
`return $this->redirectToRoute('admin_content_maintenance');`

2018-11-20 12:11 UTC, chihiro-adachi approved these changes

2018-11-21 02:09 UTC, chihiro-adachi commented
以下の事象が発生しています
- メンテナンス管理からメンテナンスを有効にする
- プラグインを有効化/無効化時に.maintenaceが削除される

2018-11-22 10:47 UTC, merged