コピーライトの更新(4.0)
EC-CUBE/ec-cube pull request #4129
Opened 2019-04-05 01:33 UTC by chihiro-adachi

株式会社ロックオンの表記を株式会社イーシーキューブへ変更

2019-04-05 04:16 UTC, kiy0taka requested changes
`src/Eccube/Resource/template/admin/login.twig` にも`LOCKON CO.,LTD.`が残ってます

2019-04-05 04:16 UTC, kiy0taka commented on html/template/admin/assets/js/file_manager.js
>   * Copyright(c) 2000-2014 LOCKON CO.,LTD. All Rights Reserved.
```Copyright(c) 2000-2014 LOCKON CO.,LTD. All Rights Reserved.``` 残ってます。

2019-04-05 04:28 UTC, chihiro-adachi commented
@k-yamamura 対応しました。

2019-04-05 04:31 UTC, kiy0taka approved these changes

2019-04-15 04:31 UTC, merged

2019-04-15 04:32 UTC, kazumiiiiiiiiiii commented
ありがとうございます！