コピーライトの更新(3.1)
EC-CUBE/ec-cube pull request #4131
Opened 2019-04-05 02:05 UTC by chihiro-adachi

株式会社ロックオンの表記を株式会社イーシーキューブへ変更

2019-04-05 04:20 UTC, kiy0taka requested changes
```
src/Eccube/Command/CsvLoaderCommand.php:5: * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
src/Eccube/Command/CsvLoaderCommand.php:7: * http://www.lockon.co.jp/
src/Eccube/Command/DocumentRootCommand.php:5: * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
src/Eccube/Command/DocumentRootCommand.php:7: * http://www.lockon.co.jp/
src/Eccube/Util/MailUtil.php:5: * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
src/Eccube/Util/MailUtil.php:7: * http://www.lockon.co.jp/
```

2019-04-05 04:26 UTC, chihiro-adachi commented
@kiy0taka 対応しました。

2019-04-05 04:31 UTC, kiy0taka approved these changes

2019-04-15 04:32 UTC, merged

2019-04-15 04:32 UTC, kazumiiiiiiiiiii commented
ありがとうございます！