PDFのロゴ画像をファイル管理から変更できる機能を追加
EC-CUBE/ec-cube pull request #4216
Opened 2019-07-08 08:12 UTC by kazumiiiiiiiiiii

## 概要(Overview・Refs Issue)
#4105 納品書に表示されているロゴの変更をファイル管理から出来るようにする

## 方針(Policy)
コンテンツ管理/ファイル管理 から、以下のパスにロゴ画像を設置することで納品書のロゴを変更できるように機能追加しました。
```
user_data/assets/pdf/logo.png
```

## 実装に関する補足(Appendix)
「user_data/assets/pdf/logo.png」にファイルが存在しない場合は、「html/template/admin/assets/pdf/logo.png」を使用するように実装しています。
また、Command、Webインストール時に「html/template/admin/assets/pdf/logo.png」を「user_data/assets/pdf/logo.png」にコピーする処理を追加しています。

## テスト（Test)
- Webインストール時のテストを追加
- CIでのテストを予定

## 相談（Discussion）
特にありません

## マイナーバージョン互換性保持のための制限事項チェックリスト
+ マイナーバージョンでは、機能・プラグイン・デザインテンプレート互換性を損なう変更は原則取り込みません。

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-07-08 23:58 UTC, chihiro-adachi requested changes

2019-07-08 23:58 UTC, chihiro-adachi commented on src/Eccube/Service/OrderPdfService.php
> +        $logoFile = $this->eccubeConfig->get('eccube_html_dir').'/'.$this->eccubeConfig->get('eccube_user_data_route').'/assets/pdf/logo.png';
`eccube_user_data_route`はページ管理のルーティングになります。
実ディレクトリが変わるわけではないので、`user_data`固定でお願いします。

2019-07-09 02:49 UTC, kazumiiiiiiiiiii reviewed
ご確認ありがとうございます。修正いたしました。

2019-07-09 04:15 UTC, chihiro-adachi approved these changes

2019-07-09 06:04 UTC, merged

2019-07-09 06:04 UTC, chihiro-adachi commented
@kazumiiiiiiiiiii ありがとうございます、マージしました。