商品CSVアップロード時、商品詳細の文字数が保存できる数を超えた場合にエラーメッセージを表示する
EC-CUBE/ec-cube pull request #4218
Opened 2019-07-09 06:29 UTC by junpeko5

## 概要(Overview・Refs Issue)
#4187 のバグ修正です。
商品詳細の文字数が、マルチバイトで4000文字を超えた場合にエラーメッセージを表示させるように修正しています。

## 方針(Policy)
DBのカラムに登録できる最大文字数を超える場合は、エラーメッセージを返すようにしました。

## 実装に関する補足(Appendix)
src/Eccube/Resource/locale/messages.ja.yaml 
src/Eccube/Resource/locale/messages.en.yaml 
にエラーメッセージを新たに追加しています。

## テスト（Test)
- アップロードするcsvファイルについて、商品詳細がマルチバイトで4000文字以内であれば、登録されることを確認しました。
- 4001文字以上の場合は、エラーとなることを画面で確認しました。

<img width="1649" alt="スクリーンショット 2019-07-09 14 55 30" src="https://user-images.githubusercontent.com/26207848/60862992-403ce600-a25a-11e9-9700-28d90e006ccc.png">

テストコードはありません。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト
+ マイナーバージョンでは、機能・プラグイン・デザインテンプレート互換性を損なう変更は原則取り込みません。

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-07-12 06:33 UTC, chihiro-adachi requested changes

2019-07-12 06:33 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.common.csv_invalid_description_detail_upper_limit: '%line%行目の%name%は4000文字以下の文字列を指定してください。'
@junpeko5 `4000`はパラメータにして切り出していただくことはできますか？lltextlenあたりをつかえばいいかなと思います。

2019-07-17 09:14 UTC, junpeko5 commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.common.csv_invalid_description_detail_upper_limit: '%line%行目の%name%は4000文字以下の文字列を指定してください。'
app/config/eccube/packages/eccube.yaml　に
`eccube_lltext_len: 99999`
`eccube_ltext_len: 3000`という項目がありましたので、
`eccube_ltext_len: 3000`をパラメーターに設定しました。3000文字以内であれば登録できるようになります。

2019-08-16 04:54 UTC, kazumiiiiiiiiiii approved these changes

2019-08-16 04:54 UTC, kazumiiiiiiiiiii commented on src/Eccube/Controller/Admin/Product/CsvImportController.php
> +                        if (isset($row[$headerByKey['description_detail']]) && mb_strlen($row[$headerByKey['description_detail']]) >= 4000) {
こちらもお願いします。

2019-08-16 09:24 UTC, chihiro-adachi commented
こちらの修正は問題ないかなと思います。

文字長についてばらついているようなので、#4275 にissueを別途作成しました。

- db上のvarcharの文字長：4000文字
- 商品登録画面でのバリデーション：3000文字(ltextlen)
- 商品csvでのバリデーション：なし→3000文字(ltextlen)

2019-08-16 09:24 UTC, chihiro-adachi approved these changes

2019-08-19 04:53 UTC, kazumiiiiiiiiiii commented
@junpeko5 のこり、テストの追加だけお願いできないでしょうか。

2019-10-28 04:37 UTC, chihiro-adachi commented
@junpeko5 
テスト追加しました。
また、3000文字がエラーになる条件になっていたので修正しています。

2019-10-28 04:37 UTC, chihiro-adachi approved these changes

2019-11-09 06:01 UTC, okazy approved these changes
動作確認をして問題ありませんでした。

2019-11-09 06:01 UTC, merged

2019-11-09 06:01 UTC, okazy commented
マージしました。ありがとうございます。