受注管理 マルチ検索の対象項目修正
EC-CUBE/ec-cube pull request #4225
Opened 2019-07-15 05:23 UTC by dk-umebius

## 概要(Overview・Refs Issue)
受注管理のマルチ検索ラベルにメールアドレス・電話番号と記載があるが検索対象になっていないため追加

![スクリーンショット 0031-07-15 14 23 04](https://user-images.githubusercontent.com/4304985/61196805-1842fc00-a70c-11e9-881b-37802da27470.png)

2019-07-16 05:20 UTC, chihiro-adachi commented
@dk-umebius 
ありがとうございます。こちらテストコード追加いただくことは可能でしょうか？

2019-07-17 01:25 UTC, dk-umebius commented
@chihiro-adachi 
了解しました、テストコード追加します。

2019-07-21 06:44 UTC, dk-umebius commented
受注管理 マルチ検索のメールアドレス・電話番号に関するテストコード追加しました。

2019-07-30 04:59 UTC, okazy commented
## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-07-30 05:01 UTC, chihiro-adachi requested changes

2019-07-30 05:01 UTC, chihiro-adachi commented on tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
> +        $this->entityManager->flush();
@dk-umebius 
こちらのflushは必要ですか？

2019-07-30 05:01 UTC, chihiro-adachi commented on tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
> +        $this->expected = 1;
assertCount使ってもらえばよいかなと思いました。

`$this->assertCount(1, $this->Results)`みたいな感じです(引数の順序はうろ覚えです。。)

2019-08-03 13:10 UTC, dk-umebius commented on tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
> +        $this->entityManager->flush();
不要ですね。testMultiWithNoのコードをコピペして削除するのを忘れていました。
元々あったtestMultiWithNoの方も要らないかと思いますので合わせて削除しました。

2019-08-03 13:12 UTC, dk-umebius commented on tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
> +        $this->expected = 1;
ありがとうございます、assertCount使用に変更しました。

2019-08-09 01:58 UTC, chihiro-adachi approved these changes

2019-08-09 01:58 UTC, merged

2019-08-09 01:58 UTC, chihiro-adachi commented
@dk-umebius ありがとうございました。