ファイル管理で複数ファイルのアップロードを実装
EC-CUBE/ec-cube pull request #4235
Opened 2019-07-20 08:45 UTC by kazumiiiiiiiiiii

## 概要(Overview・Refs Issue)
ファイル管理で複数ファイルのアップロードを実装。
#4112 

## 方針(Policy
実装時に以下の不具合を確認しIssueを追加。以下の不具合は解消しておりません。
#4234 

## 実装に関する補足(Appendix)
特になし

## テスト（Test)
テストを複数アップロードに変更して実施。

## 相談（Discussion）
特になし。

## マイナーバージョン互換性保持のための制限事項チェックリスト
+ マイナーバージョンでは、機能・プラグイン・デザインテンプレート互換性を損なう変更は原則取り込みません。

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-07-30 04:43 UTC, chihiro-adachi requested changes

2019-07-30 04:43 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Content/FileController.php
> +                $isUploaded = true;
@kazumiiiiiiiiiii 
成功/失敗のメッセージが混在することになるので、表示のしかたをご検討いただけますか。

2019-07-30 04:43 UTC, chihiro-adachi commented
@kazumiiiiiiiiiii 
複数選択できることがぱっとわからないので、ツールチップでヒント表示させておいてもらえるとありがたいです。

2019-08-02 09:41 UTC, kazumiiiiiiiiiii commented on src/Eccube/Controller/Admin/Content/FileController.php
> +                $isUploaded = true;
成功した場合のメッセージに、成功したファイルアップロード数を追加しました。
<img width="1210" alt="スクリーンショット 2019-08-02 18 37 37" src="https://user-images.githubusercontent.com/34618717/62360930-e8418880-b554-11e9-8ce0-ec9d580b6870.png">

失敗した際のエラーメッセージには、失敗したファイル名を表示するように修正を行いました。
<img width="575" alt="スクリーンショット 2019-08-02 18 37 44" src="https://user-images.githubusercontent.com/34618717/62361039-2048cb80-b555-11e9-9592-f363919d7576.png">

2019-08-02 09:43 UTC, kazumiiiiiiiiiii commented
@chihiro-adachi ツールチップ、成功/失敗のメッセージを修正いたしました。

2019-08-06 04:54 UTC, chihiro-adachi approved these changes

2019-08-06 04:55 UTC, merged

2019-08-06 04:56 UTC, chihiro-adachi commented
@kazumiiiiiiiiiii ありがとうございます。マージしました。