[WIP] GitHub Actions support
EC-CUBE/ec-cube pull request #4337
Opened 2019-09-30 11:11 UTC by nanasess

## 概要(Overview・Refs Issue)

- Github Actions で CI/CD を実行
- 以下をマトリクスで実行
  - Ubuntu 18.04
  - PostgreSQL/MySQL/SQLIte3
  - PHP7.1〜7.3

実行状況は以下を参照
https://github.com/nanasess/ec-cube/actions

## 方針(Policy)

- Travis CI でのユニットテスト、 E2Eテストを移植
- Github でリリース( or pre release)を発行すると、 tar.gz 及び zip でパッケージングし、チェックサムと共にリリースの Assets へ自動的にアップロードする

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-11-11 02:57 UTC, kiy0taka requested changes
`repos` ディレクトリはプラグインのインストールテストにしか使ってないので、リポジトリに含めずテスト時に作成するがいいと思います。

2019-11-11 06:52 UTC, nanasess commented
@kiy0taka 対応しました

2019-11-12 00:12 UTC, kiy0taka approved these changes

2019-11-12 01:18 UTC, merged

2019-11-12 01:18 UTC, chihiro-adachi approved these changes

2019-11-12 01:19 UTC, chihiro-adachi commented
@nanasess
ありがとうございます。マージしました。
しばらくは他のCIとも並行運用できればと思います。