カートに追加した商品の数量をマイナスにできてしまう問題の修正
EC-CUBE/ec-cube pull request #4341
Opened 2019-10-03 06:04 UTC by yoshiaki-natsume

## 概要(Overview・Refs Issue)

#4338 の修正PR

## 方針(Policy)

- 既存のテストがなかったので追加(他のvalidatorのテストに習って実装しました)
- 既存の実装に追加してquantityがマイナスの場合の修正実装とテストを追加

## 実装に関する補足(Appendix)

## テスト（Test)

- 既存のコードに対するテストと合わせて新しいロジックのテストも追加しました

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-10-04 01:08 UTC, chihiro-adachi commented
@yoshiaki-natsume 
初PullRequestありがとうございます🥇
修正内容確認します。何かあればコメントさせていただきますね。

2019-10-07 23:18 UTC, chihiro-adachi requested changes

2019-10-07 23:18 UTC, chihiro-adachi commented on tests/Eccube/Tests/Service/PurchaseFlow/Processor/EmptyItemsValidatorTest.php
> +        self::assertEquals(count($this->Order->getOrderItems()), 1);
assertEquals(期待値, 実行結果)なので、引数の順序が逆になってます。
件数の確認であれば、assertCount使ってもらったほうがすっきりするかもしれません。

2019-10-08 03:48 UTC, chihiro-adachi commented on tests/Eccube/Tests/Service/PurchaseFlow/Processor/EmptyItemsValidatorTest.php
> +        self::assertEquals(count($this->Order->getOrderItems()), 1);
@yoshiaki-natsume コメント記載しましたのでご確認お願いします。

2019-10-10 07:51 UTC, yoshiaki-natsume commented on tests/Eccube/Tests/Service/PurchaseFlow/Processor/EmptyItemsValidatorTest.php
> +        self::assertEquals(count($this->Order->getOrderItems()), 1);
ありがとうございます、対応しました。

2019-10-11 07:31 UTC, chihiro-adachi approved these changes

2019-10-11 07:32 UTC, chihiro-adachi commented
@yoshiaki-natsume 
ありがとうございます！マージしました。

2019-10-11 07:32 UTC, merged