Update ProductController.php
EC-CUBE/ec-cube pull request #4349
Opened 2019-10-09 01:36 UTC by Rights1995

## 概要(Overview・Refs Issue)
#4347

## 方針(Policy)
2系であった画像アップロード時のリサイズ処理について、
4系ではアップロード画像の幅、高さやサイズの指定が運用レベルで加工が必要なため
アップロード時に、パラメータで指定した画像ファイルに加工する。

## 実装に関する補足(Appendix)
アップロード後の画像サイズや、jpg、pngファイルの圧縮率の指示がベタ書きなっています。

## テスト（Test)
既に実稼働の環境での要望があり、実稼働サイトのプレビューサイトで、各画像ファイルのアップロードテストを行い、実稼働の環境に適用しています。

## 相談（Discussion）
補足にあげていますが、アップロード後の画像サイズや、jpg、pngファイルの圧縮率の指示がベタ書きなっています。設定が変更できるようになると尚良いと考えています。

2019-10-09 01:47 UTC, chihiro-adachi commented
@Rights1995 
さっそくのPullRequestありがとうございます🥇
確認してコメントさせていただきますね。

2019-10-10 04:47 UTC, chihiro-adachi commented
相談事項に書いていただいている通り、

- 縦横の画像サイズ
- 圧縮率

はパラメータ指定できたほうがよいかなと思いました。

また、リサイズが不要なケースもあるかと思いますので、リサイズのON/OFFができればと。

これくらいの仕様でどうでしょうか。

※ パラメータは、`app/config/eccube/packages/eccube.yaml`で定義することができます。

2019-10-10 04:48 UTC, chihiro-adachi requested changes

2019-10-10 04:48 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +						// 2019-10-07 Add Start
@Rights1995  こういったコメントは不要です。

2019-10-10 04:48 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +						// 加工前の画像の情報を取得
インデントは半角スペースでお願いします。

2019-10-10 04:48 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +						/* 2019-10-08 Comment Out ↓
コメントアウトの箇所は削除ください

2019-10-10 06:08 UTC, Rights1995 commented
ありがとうございます。
ご指摘の点をふまえて、手を加えてみました。

2019-10-11 08:30 UTC, chihiro-adachi requested changes

2019-10-11 08:30 UTC, chihiro-adachi commented on app/config/eccube/packages/eccube.yaml
> +    eccube_product_image_resize: true
@Rights1995 
互換性のため、デフォルトはfalseだとありがたいです。

2019-10-11 08:30 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +                                throw new RuntimeException('対応していないファイル形式です。: ', $type);
こちらのように、UnsupportedMediaTypeHttpExceptionのほうが適切かと思いました。
https://github.com/EC-CUBE/ec-cube/pull/4349/files#diff-f8468afcee7633478e8ef4896ea25c3fR330

2019-10-21 02:46 UTC, Rights1995 reviewed
ご指摘の点、修正いたしました。
ただ気になったのですが、リサイズ可否分岐のELSEの括りが必要ないように感じますが、いかがでしょうか？

2019-10-21 03:17 UTC, Rights1995 commented
> 
> 
> ご指摘の点、修正いたしました。
> ただ気になったのですが、リサイズ可否分岐のELSEの括りが必要ないように感じますが、いかがでしょうか？

2019-10-21 03:22 UTC, Rights1995 commented
失礼しました。
間違ってCloseしてしまいました。

2019-10-21 07:01 UTC, chihiro-adachi commented
@Rights1995
 
> ご指摘の点、修正いたしました。

すみません、修正が確認できず。
push いただいてますでしょうか？

> ただ気になったのですが、リサイズ可否分岐のELSEの括りが必要ないように感じますが、いかがでしょうか？

以下のelse以下が不要ということでしょうか？

https://github.com/EC-CUBE/ec-cube/pull/4349/files#diff-f8468afcee7633478e8ef4896ea25c3fR382

2019-10-21 07:50 UTC, Rights1995 commented
はい、その通りです。

2019-10-21 10:00 UTC, Rights1995 commented
> 
> 
> @Rights1995
> 
> > ご指摘の点、修正いたしました。
> 
> すみません、修正が確認できず。
> push いただいてますでしょうか？
> 
> > ただ気になったのですが、リサイズ可否分岐のELSEの括りが必要ないように感じますが、いかがでしょうか？
> 
> 以下のelse以下が不要ということでしょうか？
> 
> https://github.com/EC-CUBE/ec-cube/pull/4349/files#diff-f8468afcee7633478e8ef4896ea25c3fR382

2019-11-21 08:04 UTC, Rights1995 commented
すみません。

2019-11-22 05:13 UTC, Rights1995 commented
github-actions でBuild Failedとなっています。

2019-11-22 05:15 UTC, Rights1995 commented
github-actions で Build Failed となっています。

### ERRORED 08:48:38Z

- Workflows can't be executed on this repository. Please check your payment method or billing status.

2020-03-02 05:22 UTC, okazy commented
動作確認をして３点問題かと思われる箇所がありました。
1.  `ProductController.php` の340行目でエラー（334行目でmoveした後に `$image` を参照しているので）
2. また、`ProductController.php` の334行目でmoveした後、370行目でも保存しているため２個ファイルができてしまうかと思います。
3. 画像のクオリティではなくリサイズを変更した方が良いのではないでしょうか。

2021-02-04 03:10 UTC, Rights1995 commented
すみません。
しばらく間が開いてしまいました。
一旦クローズして再度、挙げさせていただきます。

2021-02-04 03:10 UTC, closed without merging