注文完了メールで規格名を表示できるように修正
EC-CUBE/ec-cube pull request #4386
Opened 2019-11-15 09:22 UTC by okazy

## 概要(Overview・Refs Issue)

Close #4385

`Order::getMergedProductOrderItems()` 関数で商品リストを作成時に必要事項をセットするように設定

## 方針(Policy)

規格名に加え、表示する可能性がある項目を設定

## 実装に関する補足(Appendix)

## テスト（Test)

受注完了メールで規格名が表示されることを確認

https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Resource/template/default/Mail/order.twig
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Resource/template/default/Mail/order.html.twig

注文完了メールのテンプレートに以下を追加

```php
表示される
{{ OrderItem.classcategory_name1 }}
{{ OrderItem.classcategory_name2 }}

表示されない
{{ OrderItem.class_name1 }}
{{ OrderItem.class_name2 }}
```

## 相談（Discussion）

なし

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2019-11-22 05:22 UTC, kiy0taka requested changes

2019-11-22 05:22 UTC, kiy0taka commented on src/Eccube/Entity/Order.php
> +                    ->setClassName1($ProductOrderItem->getClassName1())
Entity拡張されている場合も考慮すると、`$OrderItem->copyProperties($ProductOrderItem);` がいいと思いますが、どうでしょうか？

2019-11-26 02:32 UTC, okazy commented on src/Eccube/Entity/Order.php
> +                    ->setClassName1($ProductOrderItem->getClassName1())
ありがとうございます！ `copyProperties()` を使って書き換えました！

2019-12-02 09:06 UTC, kiy0taka approved these changes

2019-12-03 07:47 UTC, merged