ページ管理の編集対象に会員登録(確認ページ)を加える #4428
EC-CUBE/ec-cube pull request #4433
Opened 2020-01-12 12:50 UTC by oywc410

ページ管理の編集対象に会員登録(確認ページ)を加える #4428 

dtb_page変更:
edit_typeに３を追加して確認ページとして利用します。
master_page_idは確認ページのIDに設定し、ページ登録時にURLチェックを除外します。

もし仕様問題がない場合はページ一覧のデザインが調整もお願いいたします。

以上、よろしくお願いいたします。

2020-12-01 01:01 UTC, chihiro-adachi commented
フロント側のレイアウト取得が正しく取得できない問題がありました。
以下のように変更しています。

- ルーティングを`entry_confirm`のように別ルーティングを作成し、レイアウトと紐付ける
- TwigInitializeListenerでは入力画面か確認画面かの判別ができないため、レイアウトの取得はコントローラ側で制御する

2020-12-02 04:43 UTC, kiy0taka requested changes

2020-12-02 04:43 UTC, kiy0taka commented on app/DoctrineMigrations/Version20201127000000.php
> +    const NAME = 'dtb_page';
使っていない定数。

2020-12-02 04:43 UTC, kiy0taka commented on app/DoctrineMigrations/Version20201127000000.php
> +        $this->addSql("INSERT INTO dtb_page_layout (page_id, layout_id, sort_no, discriminator_type) VALUES ($pageId, 2, , $sortNo, 'pagelayout')");
syntax error

2020-12-02 05:05 UTC, chihiro-adachi commented on app/DoctrineMigrations/Version20201127000000.php
> +    const NAME = 'dtb_page';
削除しました

2020-12-02 05:05 UTC, chihiro-adachi commented on app/DoctrineMigrations/Version20201127000000.php
> +        $this->addSql("INSERT INTO dtb_page_layout (page_id, layout_id, sort_no, discriminator_type) VALUES ($pageId, 2, , $sortNo, 'pagelayout')");
修正しました

2020-12-02 05:27 UTC, kiy0taka approved these changes

2020-12-02 07:35 UTC, merged