[WIP] 管理画面の検索機能をDateTimeTypeに対応
EC-CUBE/ec-cube pull request #4619
Opened 2020-07-08 10:35 UTC by okazy

## 概要(Overview・Refs Issue)

管理画面の検索機能をDateTimeTypeに対応

close #4618 

![image](https://user-images.githubusercontent.com/16895409/86908714-f1b67600-c151-11ea-8016-4f662878865c.png)

![image](https://user-images.githubusercontent.com/16895409/86908782-0b57bd80-c152-11ea-8722-9fc9310e5dee.png)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2020-07-09 07:27 UTC, okazy commented
２点修正が必要とのご意見をいただきました。
- 時分の補完時にDateTimeTypeかどうかのチェック（Formがカスタマイズされていた場合の考慮）
- datetimepicker の初期値の設定

2020-07-09 11:06 UTC, okazy commented
クロスブラウザで日時入力UIの調整は地獄でした。

2020-07-09 12:54 UTC, k-yamamura commented
各フォームタイプにある、
```
'class' => 'datetimepicker-input',
```
も不要になったので削除しておいてください。

2020-07-10 00:30 UTC, okazy commented
@k-yamamura 
指摘ありがとうございます！

いただいた指摘を試してみたところ、入力フォームのフォーカスを解いても明示的に閉じてやらないとカレンダーが消えなくなってしまいました。

![image](https://user-images.githubusercontent.com/16895409/87103180-4ad7f400-c28f-11ea-889f-c370ae21b781.png)

原因の特定まではできなかったのですが、js で datetimepicker の対象のフォームを特定するのにも利用していますので、そのまま残す方向でどうでしょうか。

https://github.com/EC-CUBE/ec-cube/pull/4619/files#diff-81ef87e3d0e00a02b177bccd6fa3e517R47

2020-07-10 04:38 UTC, okazy commented
カレンダー入力のライブラリ自体を変更するのはどうかという提案をいただきました。
ライブラリは以下
https://flatpickr.js.org/

2020-07-10 06:06 UTC, okazy commented
カレンダー入力ライブラリの変更は影響範囲がこちらのプルリクの内容と異なりますので別でIssueを作成しました。
https://github.com/EC-CUBE/ec-cube/issues/4622

2020-07-10 06:20 UTC, kiy0taka requested changes
検索条件に登録日(終了)`2018/09/28 19:13` を指定すると、登録日が `2018/09/28 19:14` の商品が検索されてしまいます。

![image](https://user-images.githubusercontent.com/57504/87122842-9bb41080-c2c0-11ea-9dd9-a9b7b57a70cf.png)

2020-07-10 07:27 UTC, okazy commented
ありがとうございます！確認します。

2020-07-10 09:20 UTC, okazy commented
Repository を変更する方針で考えています。

```php
            $date = clone $searchData['order_date_end'];
            $date = $date
                ->modify('+1 days');
```

↓

```php
            $date = $searchData['order_date_end'];
```

`ShippingRepository->getQueryBuilderBySearchDataForAdmin()` がどこにも使われていない気がするので対応考えます。

2020-07-13 00:59 UTC, okazy commented
https://github.com/EC-CUBE/ec-cube/pull/4619#issuecomment-656577664

こちらの修正方法にしようかと思っていたのですが、Repositoryの挙動が変わるのはさすがにまずいかと思いました。
冗長にはなってしまいますが、新しいFormを追加する対応がいいかと思いましたのでそちらで実装して見ます。

2020-07-13 08:33 UTC, okazy commented
指摘いただいたこと
- 検索条件で引っかからないパターン or ２重で引っかかることはないか確認（ `<=` と `<` など）
- 今は分までとなっているが、秒まで指定したい

2020-07-13 09:32 UTC, okazy commented
> 検索条件で引っかからないパターン or ２重で引っかかることはないか確認（ <= と < など）

開始は含み: ` >= ` 
終了は含まない: ` < `

ですので漏れなくだぶりなく検索可能です。

2020-07-14 00:55 UTC, okazy commented
秒まで指定できるようにしました。

2020-07-17 02:03 UTC, kiy0taka approved these changes

2020-07-17 02:13 UTC, kiy0taka approved these changes

2020-07-21 04:34 UTC, merged