新着商品・新着情報のRSSフィード機能
EC-CUBE/ec-cube pull request #4908
Opened 2021-02-08 08:48 UTC by matsuoshi

## 概要(Overview・Refs Issue)
新着商品と、新着情報(ニュース) のRSSフィードを出力する機能を実装しました。

### 関連issue
- https://github.com/EC-CUBE/ec-cube/issues/4863

## 方針(Policy)

## 実装に関する補足(Appendix)
- テンプレートファイルの default_frame.twig に、RSSへのリンクを示すタグを追加しています
- RSSフィードへのパスは以下となります
  - /products_feed.xml
  - /news_feed.xml

## テスト（Test)
- Webテストにて 商品・新着情報とも、XML形式で内容が出力されていることを確認

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-03-09 07:21 UTC, kiy0taka commented on src/Eccube/Controller/RssFeedController.php
> +     * @Route("/products_feed.xml", name="rss_feed_for_products")
URLの拡張子は無しのほうがいいかと思います。(新着情報の方も)

2021-03-09 07:21 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Feed/news.xml.twig
> +        <lastBuildDate>{{ "now" | date(constant('DATE_RFC822')) }}</lastBuildDate>
> lastBuildDate | The last time the content of the channel changed.
https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements

なので、お知らせの最終更新日時がいいかと思います。(商品情報も同様)

2021-03-09 07:21 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Feed/news.xml.twig
> +                <guid>{{ url('homepage') }}rss/news/{{ article.id }}</guid>
> isPermaLink is optional, its default value is true. If its value is false, the guid may not be assumed to be a url, or a url to anything in particular.
https://validator.w3.org/feed/docs/rss2.html#ltguidgtSubelementOfLtitemgt

存在しないURL形式にするなら、`isPermaLink="false"` を明示的にしておいたほうが良さそうです。もしくは、商品詳細のURLにしてもいいかと思います。

2021-03-09 07:36 UTC, kiy0taka requested changes

2021-03-09 07:36 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Feed/news.xml.twig
> +        <lastBuildDate>{{ "now" | date(constant('DATE_RFC822')) }}</lastBuildDate>
`DATE_RFC822` だと年が2桁になってしまうので、`DATE_RFC2822` でお願いします。

2021-03-11 06:56 UTC, matsuoshi commented on src/Eccube/Resource/template/default/Feed/news.xml.twig
> +                <guid>{{ url('homepage') }}rss/news/{{ article.id }}</guid>
商品については商品詳細のURLにして `isPermaLink="true"` を、ニュースについては `isPermaLink="false"` を明示的に指定するようにしました。

2021-03-11 10:02 UTC, kiy0taka approved these changes

2021-03-11 10:05 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Feed/news.twig
> +                </title>
改行が入ってテストが落ちてしまっているようです。

2021-03-11 10:06 UTC, kiy0taka requested changes

2021-03-11 10:06 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Feed/news.twig
> +                </title>
改行が入ってテストが落ちてしまっているようです。

2021-03-12 03:21 UTC, matsuoshi commented on src/Eccube/Resource/template/default/Feed/news.twig
> +                </title>
@kiy0taka すいません、修正しました。

2021-03-12 07:43 UTC, kiy0taka approved these changes

2021-03-12 07:44 UTC, merged