Feature/google analytics
EC-CUBE/ec-cube pull request #4912
Opened 2021-02-12 02:38 UTC by yKazihara

## 概要(Overview・Refs Issue)
管理画面でトラッキングIDを設定し、GA計測ができるようにしました。

### 関連Issue
#4837

## 方針(Policy)
トラッキングIDの登録は、管理画面の設定＞店舗設定＞基本設定に追加しました。

## 実装に関する補足(Appendix)
特になし

## テスト（Test)
トラッキングIDの登録ありなしで、フロント側のスクリプト表示非表示のテストを追加しました。

## 相談（Discussion）
特になし

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-02-15 06:27 UTC, chihiro-adachi requested changes

2021-02-15 06:27 UTC, chihiro-adachi commented on tests/Eccube/Tests/Web/TopControllerTest.php
> +        $BaseInfo = $this->container->get(BaseInfoRepository::class)->get();
@yKazihara  
$this->entityManager->getRepository(BaseInfoRepository::class)が望ましいです。

https://doc4.ec-cube.net/update-40-41#%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%81%8B%E3%82%89%E3%81%AE%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E5%8F%96%E5%BE%97%E3%81%AE%E5%88%B6%E9%99%90

2021-02-15 06:46 UTC, chihiro-adachi requested changes

2021-02-15 06:46 UTC, chihiro-adachi commented on src/Eccube/Entity/BaseInfo.php
> +        private $ga_id;
キャメルケースでお願いします。

2021-02-15 06:49 UTC, chihiro-adachi requested changes

2021-02-15 06:49 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/default_frame.twig
> +    {% if BaseInfo.ga_id is not empty %}
@yKazihara 
default_frame.twigは管理画面から編集できないので、gtagの記述はブロック機能に持っていくほうがよいかもしれません。

2021-02-16 08:30 UTC, yKazihara commented on tests/Eccube/Tests/Web/TopControllerTest.php
> +        $BaseInfo = $this->container->get(BaseInfoRepository::class)->get();
ありがとうございます。修正しました。

2021-02-16 08:32 UTC, yKazihara commented on src/Eccube/Entity/BaseInfo.php
> +        private $ga_id;
ありがとうございます。修正しました。

2021-02-16 08:33 UTC, yKazihara commented on src/Eccube/Resource/template/default/default_frame.twig
> +    {% if BaseInfo.ga_id is not empty %}
ありがとうございます。ブロック機能に切り出しました。

2021-03-15 11:44 UTC, okazy reviewed
英語の言語ファイルにも追加をお願いします。
`src/Eccube/Resource/locale/messages.en.yaml`

2021-03-15 11:44 UTC, okazy commented on src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
> +                        <div id="ex-shop-point" class="card-body">
id がページ内で重複していますので一意になるようにお願いします。

2021-03-16 01:18 UTC, yKazihara commented on src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
> +                        <div id="ex-shop-point" class="card-body">
確認ありがとうございます。idを修正しました。

2021-03-16 01:32 UTC, okazy commented on src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
> +                        <div id="ex-shop-point" class="card-body">
ありがとうございます！修正を確認しました。

2024-02-26 12:42 UTC, shinya commented
@chihiro-adachi @dotani1111 @ji-eunsoo 
4.3αのコードを取り込み直しました。テストも通ったので、改めてレビューお願いします。

2024-02-29 02:38 UTC, ji-eunsoo commented
@shinya 
GAのトラッキングが通っていることのご確認をお願い致します。

2024-03-01 00:13 UTC, shinya commented
<img width="486" alt="スクリーンショット 2024-03-01 9 07 08" src="https://github.com/EC-CUBE/ec-cube/assets/8691817/75e57203-a65f-43c4-a7d1-a7f48276d4e3">

GA上でもアクセスが来ることを確認できました

2024-03-01 00:46 UTC, k-yamamura commented
googleアナリティクスを導入する際にプライバシーポリシーに以下の記述が必要となりますが、
考慮する必要はないでしょうか。
https://support.google.com/analytics/answer/7318509?hl=ja

2024-03-06 07:50 UTC, shinya commented
@k-yamamura 
ありがとうございます。確かに考慮する必要ありだと感じました。
こちら一旦預かってやり方検討いたします。

2024-03-07 05:22 UTC, shinya commented
WebサイトにGoogleAnalytics（以下GA）を導入する場合、
・GAを使ってトラッキングしていること
・そのトラッキングのためにCookieを使っていること
・収集したデータの保存・処理方法の説明（GAの[規約リンク](https://marketingplatform.google.com/about/analytics/terms/jp/)を貼るでもOK）
の記載が必要です。

しかし、GAのID発行の際に上記の必要性は使用者（この場合GAの使用者なのでサイトオーナーを指す）に通知されるため、
EC-CUBEが特別それを考慮する必要はないと感じました。
（ようはこの規約を知らずにサイトにGAを導入することはありえない）

また、本機能はあくまでタグの導入を支援する位置づけのものであり、
上記の規約云々を理解したユーザーがHTMLを直接する手間を軽減する目的で実装します。

とはいえ、何もしないのはさすがに不親切なのでユーザーが情報を調べられるようにはしておきたい。

**以上の理由から、EC-CUBE内での対応は下記で行こうと考えています**。
・管理画面内のtooltipにはGAの規約を満たしたうえで使用するよう文言を変える
・[doc4](https://doc4.ec-cube.net/)と[運用マニュアル](https://www.ec-cube.net/manual/ec-cube4/)にそれぞれ使い方を記載しておく

ご意見ください。
問題なければそれで対応を進めます。

2024-04-04 07:32 UTC, dotani1111 commented
動作確認OKでした。

2024-04-04 07:34 UTC, dotani1111 commented
@chihiro-adachi 
こちら問題なければApproveをお願い致します。

2024-04-08 05:19 UTC, chihiro-adachi approved these changes

2024-04-08 05:19 UTC, dotani1111 approved these changes

2024-04-08 05:20 UTC, merged