新着商品ブロックにて、商品を動的に表示する
EC-CUBE/ec-cube pull request #4920
Opened 2021-02-15 04:55 UTC by matsuoshi

## 概要(Overview・Refs Issue)
デフォルトでTOPページに表示される「新着商品」ブロックにて、動的に新着商品を表示するようにしました。

(現状は、商品がHTMLでハードコードされており、新着商品の更新にはブロック内のHTMLの編集が必要)

### 関連issue
https://github.com/EC-CUBE/ec-cube/issues/4858
https://github.com/EC-CUBE/ec-cube/issues/4623
https://github.com/EC-CUBE/ec-cube/issues/4504

## 方針(Policy)
作成日の新しいものから順に、最大5件の商品を自動表示。

## 実装に関する補足(Appendix)
データの取得方法は、既存の Newsブロックと同様にtwig内からリポジトリにアクセスしています。

## テスト（Test)
ブロックが表示されることを確認するWebテストを追加しました。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-02-15 06:45 UTC, chihiro-adachi requested changes

2021-02-15 06:45 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.en.yaml
> -front.block.new_item.item_1_name: "Colorful Gelato: 'CUBE'"
@matsuoshi 
該当テンプレートを管理画面で更新していた際に、メッセージIDがそのまま表示されてしまうので、削除ではなくdeprecatedにしておいてもらえるとありがたいです。
https://github.com/EC-CUBE/ec-cube/blob/4.0/src/Eccube/Resource/locale/messages.ja.yaml#L109

2021-02-15 06:45 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Block/new_item.twig
> +{% set Products = repository('Eccube\\Entity\\Product').findBy(
@matsuoshi 
商品一覧を取得する際は、在庫なし商品の非表示のオプションも考慮する必要があります。
ProductRepisitory::getQueryBuilderBySearchDataの利用をお願いします。

2021-02-16 07:10 UTC, k-yamamura commented
サイトによってはカラー違いで同一商品が並ぶというような事も起きるため、
既存のブロックはそのまま残しておいて手動で修正できるようにしておき、
新たなブロックとして定義する方が良いのでは無いでしょうか。

2021-02-17 05:44 UTC, matsuoshi commented
@k-yamamura コメントありがとうございます！
今回のブロックは既存ブロックをベースにループを足した形ですので、手動で運用したい場合でも修正負荷はさほど高くないと考えています。

手動で運用したい場合はいずれにせよブロックの修正は必須になりますので、手動更新したいユーザ／しないユーザ別にブロックを2つ用意するのは冗長かとも思ったのですが、いかがでしょうか。

2021-02-18 05:37 UTC, matsuoshi commented on src/Eccube/Resource/locale/messages.en.yaml
> -front.block.new_item.item_1_name: "Colorful Gelato: 'CUBE'"
こちら修正しました。

2023-07-07 01:19 UTC, xuelian311 commented
@Yangsin @kiy0taka @chihiro-adachi 実装方針として、今のブラックを修正するより、新しく動的ブロックを追加するのはいかがでしょうか？

2023-07-07 03:45 UTC, Yangsin commented
マイナーバージョンで対応する場合は、新規追加でなければ、既存への影響がでますのでNGと考えます。
ブロックはプラグインや普段の運用でも結構追加されたりもするので、その点の影響も注意が必要かと。

2024-03-06 07:40 UTC, shinya commented
今回、4.3へのアップデートなので取り込み対象にします。
ただし、ブロックを新しく追加する形に変更したいと思います。
そのためソースコードをいくつか変更することになるかと思います。
また、性能に変化が出そうな部分になるのでその辺りも考慮に入れて改修を行います。

2024-03-13 07:04 UTC, shinya commented
こちら新しい要素として書き換えました。
（デフォルトのブロックとしては入れずに手動で追加すれば表示される）
確認よろしくお願いします。

2024-03-20 23:13 UTC, chihiro-adachi approved these changes

2024-03-21 01:29 UTC, chihiro-adachi commented
確認しました。問題ないです。

2024-03-22 01:29 UTC, dotani1111 commented
@shinya 
テストが落ちてしまう問題の修正を行いました。
こちらの取り込みと、自動表示の方へ文言変更をお願いします。

2024-04-01 05:13 UTC, shinya approved these changes

2024-04-01 05:30 UTC, merged