Doctrine ORM3.0ではサポートされないので、flushにエンティティを指定している処理を修正。
EC-CUBE/ec-cube pull request #4925
Opened 2021-02-17 01:57 UTC by kurozumi

## 概要(Overview・Refs Issue)

Doctrine ORM3.0ではサポートされないので、
flushにエンティティを指定している処理部分をpersistまたはremoveでエンティティを指定してflushするよう変更しました。

https://github.com/doctrine/orm/blob/ebae57eb9637acd8252b398df3121b120688ed5c/lib/Doctrine/ORM/EntityManager.php#L367-L372

https://github.com/doctrine/orm/issues/8459

※EC-CUBE4.0ではDoctrine ORM3.0をサポートしない気がするのですがいかがでしょうか？

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-02-17 03:03 UTC, nanasess commented
> ※EC-CUBE4.0ではDoctrine ORM3.0をサポートしない気がするのですがいかがでしょうか？

#4528 でも ORM2.8 にしているので、 ORM 3.0 への対応は当分先になるかもしれません。
が、この PR を取り込められれば、 #4528 での ORM 3.0 のサポートが前進しそうです。

2021-03-09 23:48 UTC, matsuoshi approved these changes
ありがとうございます、内容問題ないと思います

2021-03-10 02:13 UTC, okazy commented
こちらのテストが落ちていました。
テストを再実行してみます。

```
1) EF03OrderCest: Ef0303-uc01-t01_購入フローでログインしたタイミングで複数カートになったらログイン後にカート画面に戻す
 Test  codeception/acceptance/EF03OrderCest.php:order_ログイン後に複数カートになればカートに戻す
 Step  See "同時購入できない商品がカートに含まれています",".ec-alert-warning__text"
 Fail  Element located either by name, CSS or XPath element with '.ec-alert-warning__text' was not found.
```

2021-03-10 10:50 UTC, okazy commented
また以下でテストが落ちました。

>EF03OrderCest: Ef0303-uc01-t01_購入フローでログインしたタイミングで複数カートになったらログイン後にカート画面に戻す

原因を調査してから取り込みたいです。

2021-03-16 02:10 UTC, okazy requested changes
解決策は調査中ですが、このままでは取り込めないのでレビューステータスを変えておきます。

2021-03-16 02:10 UTC, okazy commented on src/Eccube/Service/CartService.php
> +            $this->entityManager->flush();
ログイン時にカートが別れる場合にエラーが発生します。

![image](https://user-images.githubusercontent.com/16895409/111245449-fcfa6380-8647-11eb-9fc3-63a9582722d1.png)

2021-03-16 02:49 UTC, okazy commented
@kurozumi 
テストが落ちていたので修正のプルリクをお送りしました。
https://github.com/kurozumi/ec-cube/pull/6
ご確認とマージをお願いできますでしょうか。

2021-03-16 06:02 UTC, kurozumi commented
@okazy 

ありがとうございます。反映しました。

2021-03-16 06:04 UTC, okazy approved these changes
ありがとうございます！

2021-03-16 06:06 UTC, merged