商品画像アップロード即削除時の挙動を修正
EC-CUBE/ec-cube pull request #4935
Opened 2021-02-22 08:11 UTC by izayoi256

## 概要(Overview・Refs Issue)

#4848

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-03-01 11:48 UTC, okazy requested changes

2021-03-01 11:48 UTC, okazy commented on src/Eccube/Controller/Admin/Product/ProductController.php
@izayoi256 

```suggestion
                $this->entityManager->flush();
```

新しい画像を登録する際、一度ここで永続化しておかないと、567行目の `findOneBy` で Entity が取得できずにエラーとなりました。

2021-03-01 11:50 UTC, okazy commented
上記の指摘以外は動作、コード共に問題ありませんでした。
画像の削除ロジックもより正しいロジックに変更いただいています。

2021-03-02 01:26 UTC, izayoi256 commented
あぁ、 この時点では`ProductImage`が `flush`されてなかったんですね、失礼しました。
修正してpushしました。

2021-03-09 06:00 UTC, okazy approved these changes
ありがとうございます！
確認できました。

2021-03-11 05:56 UTC, merged

2021-03-11 05:56 UTC, okazy commented
ありがとうございます！取り込みました。