[WIP] 定休日カレンダー機能を実装
EC-CUBE/ec-cube pull request #4974
Opened 2021-03-17 07:05 UTC by yKazihara

## 概要(Overview・Refs Issue)
管理画面で定休日を設定し、フロントのブロックで2ヶ月分の営業日カレンダーを表示できるようにしました。

関連Issue
#4420 

## 方針(Policy)
- 管理画面で定休日の個別設定(登録・修正・削除)が可能
   ![image](https://user-images.githubusercontent.com/18630259/111427344-542c3100-8739-11eb-9347-e2b581738dfa.png)

  - 管理画面＞設定＞店舗設定　に「定休日カレンダー設定」メニューを追加
  ![image](https://user-images.githubusercontent.com/18630259/111426473-0d8a0700-8738-11eb-87fa-d6c8f7822348.png)

  - 曜日設定は対応していません
  - csvファイルアップロードでの一括登録には対応していません
  - csvのエクスポートには対応していません
  - 既に導入されている定休日カレンダープラグインなどのデータ引き継ぎには対応していません
  - 既にカレンダーのプラグイン導入や実装をされている場合を考慮して、初期表示は行いません
  - コンテンツ管理＞レイアウト管理から、カレンダーブロックをドラッグ＆ドロップし適宜配置していただく想定にしています

## 実装に関する補足(Appendix)
- フロントのカレンダーのスタイル実装はこれから対応します
   キャプチャは新着情報の下にカレンダーブロックを配置した場合。
   スタイルを当てる前のサンプルです。赤字が定休日、黄色のセルが本日です。
   ![image](https://user-images.githubusercontent.com/18630259/111428027-504cde80-873a-11eb-80ab-8875624c0100.png)

## テスト（Test)
- テストはこれから実装します

## 相談（Discussion）
既存機能とぶつからないように(カレンダーが2個表示されるなど)ブロックで実装していますが、プラグインの方がよい、本体に追加だとこんなデメリットがある、などありましたらぜひお知らせ下さい。

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-03-24 08:19 UTC, chihiro-adachi commented
編集時に重複エラーが発生します。
登録→鉛筆をクリック→決定で、重複エラーが発生。

2021-03-24 08:20 UTC, chihiro-adachi commented
削除メッセージでIDが表示されているようです。
`この操作はあとから取り消すことができません。「2」を削除してよろしいですか？`

2021-03-24 08:25 UTC, chihiro-adachi commented
side_left/rightに配置した場合に上下で表示がずれます。
※トップページに配置する前提かと思うのですが、2系でわりと多い配置なので、対応できば使い勝手はよいかなと思いました

![image](https://user-images.githubusercontent.com/8196725/112278002-b5b64780-8cc5-11eb-8f61-ae10f3ed1c1e.png)

2021-03-24 08:34 UTC, chihiro-adachi commented
曜日設定がないのであれば、土日はデフォルトで赤表示にし、twigで編集可能な状態にしておくとよいかなと思いましたがいかがでしょう。

2021-03-24 23:54 UTC, yKazihara commented
@chihiro-adachi 
コメントありがとうございます。以下を修正しました。
- 編集時に重複エラーとなる件
　編集ではエラーとならないようにしました。
- 削除のメッセージがIDになっている件
　タイトルを表示するようにしました。

スタイル調整と土日を最初から定休日としておく件はのちほど対応いたします。

2021-03-25 05:04 UTC, yKazihara commented
@chihiro-adachi 
スタイル調整と土日を最初から定休日としておく件、対応しました。
方針の説明などもアップデートしております。
テストについてはこれから修正します。

2021-03-25 23:30 UTC, yKazihara commented
Webテスト修正済です。
PHPUnitテストがいくつか落ちているので確認します。

2021-03-26 01:43 UTC, yKazihara commented
Webテストを検証していたところ、タイムゾーンの扱いの課題が見つかりました。
一旦WIPに戻させていただきます。

2021-03-29 23:52 UTC, chihiro-adachi requested changes

2021-03-29 23:52 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Block/calendar.twig
> +        * 赤字は休業日です。<br>
@yKazihara 
message.yamlへの切り出しをお願いします。

2021-03-29 23:54 UTC, chihiro-adachi commented
@yKazihara 
コメント内容修正されているのを確認しました。動作も問題ありません。
`* 赤字は休業日です`だけ修正お願いします。

2021-03-30 00:48 UTC, yKazihara commented on src/Eccube/Resource/template/default/Block/calendar.twig
> +        * 赤字は休業日です。<br>
確認いただきありがとうございます。
文言を切り出しました。

2021-11-22 02:17 UTC, nanasess requested changes
@yKazihara いくつかコメント入れましたのでご確認お願いします

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/CalendarController.php
> +     * @Route("/%eccube_admin_route%/setting/shop/calendar", name="admin_setting_shop_calendar")
`methods={"GET", "POST"}` を指定お願いします

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Controller/Block/CalendarController.php
> +     * @Route("/block/calendar", name="block_calendar")
`methods={"GET"}` を追記お願いします

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Controller/Block/CalendarController.php
> +        $thisMonthTitle = $firstDateOfThisMonth->format('Y年n月');
メッセージリソースの使用をお願いします

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Entity/Calendar.php
> +         * @var integer
```suggestion
         * @var int
```

`@var int` が正しいです

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Repository/CalendarRepository.php
> +        return $this->find($id);
```suggestion
        return $calendar;
```

`return $calendar;` で良いと思います

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Repository/CalendarRepository.php
> +     * @param int|Calend $Calendar
```suggestion
     * @param int|Calendar $Calendar
```

`* @param int|Calendar $Calendar` が正しいと思います

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Resource/template/default/Block/calendar.twig
> +                    <th class="ec-calendar__sun">日</th>
メッセージリソースを使用する必要がありそうです

2021-11-22 02:17 UTC, nanasess commented on src/Eccube/Resource/template/default/Block/calendar.twig
> +                    <th class="ec-calendar__sun">日</th>
メッセージリソースを使用する必要がありそうです

2021-11-22 02:17 UTC, nanasess commented on tests/Eccube/Tests/Repository/CalendarRepositoryTest.php
> + * TaxRuleRepository test cases.
```suggestion
 * CalendarRepository test cases.
```

2021-11-22 02:17 UTC, nanasess commented on tests/Eccube/Tests/Repository/CalendarRepositoryTest.php
> + * @author Kentaro Ohkouchi
```suggestion
 * @author Yuko Kajihara
```

2021-11-24 10:59 UTC, matsuoshi commented
@nanasess 確認ありがとうございます、ひととおり修正反映しました

2021-11-25 07:05 UTC, nanasess approved these changes

2021-11-30 00:07 UTC, chihiro-adachi approved these changes

2021-11-30 06:45 UTC, carkn commented
動作確認を行いました。問題ないかと思います。
マージします。

2021-11-30 06:45 UTC, merged

2021-12-02 10:49 UTC, k-yamamura commented
getHolidayListに
```
useResultCache(true, $this->getCacheLifetime())
```
も実装して欲しいですが不要なのでしょうか。

後すごい今更ですが、2系とEntity名や仕様を合わせてほしかったなと思います。