[WIP] 商品詳細ページに構造化データを追加
EC-CUBE/ec-cube pull request #4986
Opened 2021-03-24 08:15 UTC by matsuoshi

## 概要(Overview・Refs Issue)
4.1 feature 向けのPRです。

商品詳細ページに、構造化データ (JSON-LD形式) を埋め込みます

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-06-24 08:40 UTC, chihiro-adachi requested changes

2021-06-24 08:40 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +                "{{ app.request.schemeAndHttpHost }}{{ asset(no_image_product, 'save_image') }}"
画像のURLが以下のように出力されてました。
`http://127.0.0.1:8080/html/upload/save_image/`

no_image_productはtwigフィルタなので、以下のように渡してください
`{{ asset(''|no_image_product, 'save_image') }}`

2021-06-24 08:40 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +        "description": "{{ Product.description_list | default(Product.description_detail) | striptags | replace({'\n': '', '\r': ''}) }}",
descriptionは文字長の制限はありますか？
制限あれば文字長内に丸めるなどしたほうがよいかもしれません。

2021-06-24 08:40 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +        "sku": "{{ Product.code_min }}",
商品コードは未設定の場合がありますが、skuは空でも問題ないですか？

2021-06-24 08:47 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +        "description": "{{ Product.description_list | default(Product.description_detail) | striptags | replace({'\n': '', '\r': ''}) }}",
いくつかの文字種が期待通りに出力されないかもです。

`'あああ'` -> `&#039;あああ&#039;`
`"あああ"` -> `&quot;あああ&quot;`
`<今ならお買い得！>` -> ` `

そこまで厳密にする必要はないかもしれませんがいちおう。

2021-07-01 03:38 UTC, matsuoshi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +        "description": "{{ Product.description_list | default(Product.description_detail) | striptags | replace({'\n': '', '\r': ''}) }}",
> descriptionは文字長の制限はありますか？

仕様上の上限が見当たりませんでしたが、確かに全文出す必要はないと思いますので metaタグのdescription などで一般的な 300文字に丸めます

2021-07-01 03:38 UTC, matsuoshi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +        "sku": "{{ Product.code_min }}",
sku は構造化データの仕様では「任意」でしたので、未設定の場合は出力しないよう変更しました

2021-07-01 03:39 UTC, matsuoshi commented on src/Eccube/Resource/template/default/Product/detail.twig
> +        "description": "{{ Product.description_list | default(Product.description_detail) | striptags | replace({'\n': '', '\r': ''}) }}",
`'` `"` については、テストツールで検証したところ正しく解析されていたようのですので、このままにします。
https://search.google.com/test/rich-results
`<>` について、striptags は副作用ありそうなので削除しました。(description内の不等号はエスケープされて出力される形)

2021-07-02 00:04 UTC, merged

2021-07-02 00:05 UTC, chihiro-adachi commented
@matsuoshi 
ありがつございます、マージしました

2021-07-02 02:10 UTC, k-yamamura commented
今更ですが、
```
{{ app.request.schemeAndHttpHost }}{{ asset(img, 'save_image') }}
```
と絶対URLで記述する必要がある箇所ですが、 #5057 に記述している、`{{ absolute_url() }}` を使った
```
absolute_url(asset(img, 'save_image'))
```
を利用するか、EC-CUBEとしてどちらかで統一しておいた方が良さそうなのと、フルパスで記述する場合、
```
{{ app.request.schemeAndHttpHost }}{{ app.request.basePath }}{{ asset(img, 'save_image') }}
```
と環境によっては`{{ app.request.basePath }}`が必要です。