Generator で Product 作成時に ProductTag もセットする
EC-CUBE/ec-cube pull request #4990
Opened 2021-03-26 05:38 UTC by okazy

## 概要(Overview・Refs Issue)

Generator で Product 作成時に ProductTag もセットするようにしました。

Tag管理機能は3系の初期にはなかった機能なので実装されていませんでした。
refs https://github.com/EC-CUBE/ec-cube/pull/2657

## テスト（Test)

ローカルで商品を生成して確認

![image](https://user-images.githubusercontent.com/16895409/112587399-db1b9080-8e40-11eb-9c08-621e15fd2d71.png)

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-03-26 06:44 UTC, nanasess requested changes

2021-03-26 06:44 UTC, nanasess commented on tests/Eccube/Tests/Fixture/Generator.php
> +            $this->entityManager->flush($ProductTag);
flush の引数は非推奨かなと
https://github.com/EC-CUBE/ec-cube/pull/4925

2021-03-26 07:11 UTC, okazy commented
テストめっちゃ落ちていたので直しました。

<details>
  <summary>エラー折りたたみ</summary>

```
There were 2 errors:

1) Eccube\Tests\Repository\ProductRepositoryGetQueryBuilderBySearchDataTest::test300ProductsList
Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'DELETE FROM dtb_product':

SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "dtb_product" violates foreign key constraint "fk_4433e7214584665a" on table "dtb_product_tag"
DETAIL:  Key (id)=(493) is still referenced from table "dtb_product_tag".

/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:48
/home/runner/work/ec-cube/ec-cube/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php:98
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:145
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:162
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/EccubeTestCase.php:249
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataTest.php:359

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "dtb_product" violates foreign key constraint "fk_4433e7214584665a" on table "dtb_product_tag"
DETAIL:  Key (id)=(493) is still referenced from table "dtb_product_tag".

/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:153
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/EccubeTestCase.php:249
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataTest.php:359

Caused by
PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "dtb_product" violates foreign key constraint "fk_4433e7214584665a" on table "dtb_product_tag"
DETAIL:  Key (id)=(493) is still referenced from table "dtb_product_tag".

/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:153
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/EccubeTestCase.php:249
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataTest.php:359

2) Eccube\Tests\Web\CartValidationTest::testProductInCartDeleted
Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'DELETE FROM dtb_product':

SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "dtb_product" violates foreign key constraint "fk_4433e7214584665a" on table "dtb_product_tag"
DETAIL:  Key (id)=(1517) is still referenced from table "dtb_product_tag".

/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:48
/home/runner/work/ec-cube/ec-cube/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php:98
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:145
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:162
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/EccubeTestCase.php:249
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Web/CartValidationTest.php:2725
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Web/CartValidationTest.php:139

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "dtb_product" violates foreign key constraint "fk_4433e7214584665a" on table "dtb_product_tag"
DETAIL:  Key (id)=(1517) is still referenced from table "dtb_product_tag".

/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:153
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/EccubeTestCase.php:249
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Web/CartValidationTest.php:2725
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Web/CartValidationTest.php:139

Caused by
PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "dtb_product" violates foreign key constraint "fk_4433e7214584665a" on table "dtb_product_tag"
DETAIL:  Key (id)=(1517) is still referenced from table "dtb_product_tag".

/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
/home/runner/work/ec-cube/ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:153
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/EccubeTestCase.php:249
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Web/CartValidationTest.php:2725
/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Web/CartValidationTest.php:139

--

There was 1 failure:

1) Eccube\Tests\Doctrine\ORM\Tools\PaginationTest::testWhereWithJoinEntity
Failed asserting that false is true.

/home/runner/work/ec-cube/ec-cube/tests/Eccube/Tests/Doctrine/ORM/Tools/PaginationTest.php:275

ERRORS!
Tests: 1923, Assertions: 3207, Errors: 2, Failures: 1, Skipped: 11, Incomplete: 75.

Remaining deprecation notices (85627)
Error: Process completed with exit code 2.
```

</details>

2021-03-26 07:17 UTC, okazy commented on tests/Eccube/Tests/Fixture/Generator.php
> +            $this->entityManager->flush($ProductTag);
すみません、甘えてしまいました。
https://github.com/EC-CUBE/ec-cube/pull/4990/commits/d4a9df7cda0028aa225c490f40afd6f3bb0d9c27

2021-03-26 07:56 UTC, nanasess approved these changes

2021-11-24 07:16 UTC, merged

2021-11-24 07:17 UTC, matsuoshi commented
@okazy ありがとうございます、こちらマージいたします