キャッシュ削除時のメンテナンスタイミングを調整
EC-CUBE/ec-cube pull request #5092
Opened 2021-07-15 09:20 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

#4831

プラグインのインストール時など、メンテナンス解除のタイミングが早すぎるため、キャッシュが破損する場合がある。

現状のフローは以下の通り。
3のタイミングでメンテナンスが解除されるため、フロントからのアクセスが発生しているとキャッシュが破損する場合がある。

<img src="https://user-images.githubusercontent.com/8196725/125762033-faa483ae-1d59-4d8c-afea-6b4a1fc3a9a6.png" width="400px">

## 方針(Policy)

キャッシュが生成されるまで、メンテナンス状態を維持する。
キャッシュ削除後、ajaxの別リクエストでメンテナンス解除をするように対応。

<img src="https://user-images.githubusercontent.com/8196725/125762949-2b8cceae-397c-4455-a209-68c9835c452f.png" width="400px">

以下の機能で対応しています。
- プラグインのインストール/有効化/無効化/削除
- コンテンツ管理＞キャッシュ削除

## 実装に関する補足(Appendix)

権限管理設定でアクセス不可になるのを避けるため、メンテナンス管理のルーティングは/admin/disable_maintenanceで設定しています

## テスト（Test)

- メンテナンス管理のユニットテストを追加
- 
## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更
- [ ] フックポイントの呼び出しタイミングの変更
- [ ] フックポイントのパラメータの削除・データ型の変更
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [ ] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-07-15 09:29 UTC, nanasess commented
この warmup もあった方が嬉しい気がします
https://github.com/EC-CUBE/ec-cube/commit/be0f33e9b087dd221d0a0af8cdb1782a46dda8d5

2021-07-15 23:06 UTC, chihiro-adachi commented
@nanasess 
ありがとうございます。

メンテナンス解除のリクエストでキャッシュ生成も同時に行われるので、明示的にwarmupするのは入れませんでした。
動作上も(Apache + mod_phpですが)問題なかったため、明示的なwarmupはなくてもよいかなと思っています。

2021-07-21 05:09 UTC, kiy0taka requested changes

2021-07-21 05:09 UTC, kiy0taka commented on src/Eccube/Resource/template/admin/Content/cache.twig
> +        {% for message in app.flashes('eccube.admin.disable_maintenance') %}
`for` ではなくて `if` の方が適切かと思います。またこの分岐は `<script>` の前においてください。

2021-07-21 05:09 UTC, kiy0taka commented on src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
> +                $.post("{{ url('admin_disable_maintenance', { 'mode': 'auto_maintenance' }) }}").then(function() {
削除に失敗すると `admin_disable_maintenance` も失敗する可能性があるので、rejectされたときの処理も必要かと思います。

2021-07-21 05:09 UTC, kiy0taka commented on src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
> +    {% for message in app.flashes('eccube.admin.disable_maintenance') %}
これも `if` が適切かと思います。

2021-07-21 06:15 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Content/cache.twig
> +        {% for message in app.flashes('eccube.admin.disable_maintenance') %}
修正しました

2021-07-21 06:16 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
> +                $.post("{{ url('admin_disable_maintenance', { 'mode': 'auto_maintenance' }) }}").then(function() {
修正しました
モーダルのロック解除してからadmin_disable_maintenanceするように制御順を変更してます。

2021-07-21 06:16 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
> +    {% for message in app.flashes('eccube.admin.disable_maintenance') %}
修正しました

2021-07-21 07:14 UTC, kiy0taka commented on src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
> +                $.post("{{ url('admin_disable_maintenance', { 'mode': 'auto_maintenance' }) }}");
既存の動作としては、インストール/有効化/無効化/削除のすべてにおいて処理が失敗したときはメンテナンスモードのままになっていると思います。
この修正では削除時だけ失敗してもメンテナンス解除するようになりますが、意図したものでしょうか？既存に合わせる必要はないかと思いますが、統一はしておきたいと思います。

2021-07-21 07:20 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
> +                $.post("{{ url('admin_disable_maintenance', { 'mode': 'auto_maintenance' }) }}");
意図したものではないですね。こちら把握してなかったです。
> 既存の動作としては、インストール/有効化/無効化/削除のすべてにおいて処理が失敗したときはメンテナンスモードのままになっていると思います。

削除失敗時のメンテナンス解除処理は行わず、メンテナンスモードのままにするよう修正しています。

2021-07-28 02:53 UTC, kiy0taka approved these changes

2021-07-28 02:53 UTC, merged