E2E EA06 incomplete 項目の対応
EC-CUBE/ec-cube pull request #5167
Opened 2021-09-16 01:54 UTC by matsuoshi

2021-09-21 09:20 UTC, kiy0taka requested changes

2021-09-21 09:20 UTC, kiy0taka commented on codeception/acceptance/EA06ContentsManagementCest.php
> +        $I->grabTextFrom('.ec-layoutRole__header .ec-headerTitle');
> 5. ページ管理にて作成したレイアウトを適用し、ページURLへ遷移すると編集した内容のレイアウトが表示される

タイトルを取得してるだけなので、レイアウトの検証をできるように修正お願いします。

2021-09-21 09:20 UTC, kiy0taka commented on codeception/acceptance/EA06ContentsManagementCest.php
> +        $I->grabTextFrom('.ec-layoutRole__contentTop .ec-headerTitle');
こちらも同様にレイアウトの検証をお願いします。

2021-09-22 02:11 UTC, matsuoshi commented on codeception/acceptance/EA06ContentsManagementCest.php
> +        $I->grabTextFrom('.ec-layoutRole__header .ec-headerTitle');
@kiy0taka 新着情報ブロックをヘッダ → フッタへと移動させ、期待している位置に出力されているかどうか確認するよう、修正しました

2021-09-22 05:00 UTC, kiy0taka approved these changes

2021-09-22 05:00 UTC, merged