ItemValidatorでProductClassがvisibleかチェック
EC-CUBE/ec-cube pull request #5211
Opened 2021-11-12 03:40 UTC by dk-umebius

## 概要(Overview・Refs Issue)
#5210 

## 方針(Policy)
下記の場合、_「商品名(規格名含む)」は現時点で購入できません。該当商品をカートから削除しました。_ と表示され商品がカートから削除される。
・無効な商品規格をカートに追加する
・カートに追加している商品規格が無効に設定変更される

## テスト（Test)
・無効にした商品企画を注文履歴から再注文
・カートに追加済みの商品を無効に変更する

## 相談（Discussion）
ProductStatusValidatorに追記したのですが、新規クラスの方が良いでしょうか？

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更
- [x] フックポイントの呼び出しタイミングの変更
- [x] フックポイントのパラメータの削除・データ型の変更
- [x] twigファイルに渡しているパラメータの削除・データ型の変更
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更
- [x] 入出力ファイル(CSVなど)のフォーマット変更

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか

2021-11-17 08:03 UTC, chihiro-adachi commented
@dk-umebius 
prありがとうございます。
ユニットテストがおちているのでご確認お願いできますでしょうか。
https://github.com/EC-CUBE/ec-cube/runs/4185787650?check_suite_focus=true

2021-11-17 08:04 UTC, chihiro-adachi requested changes

2021-11-17 08:04 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.ja.yaml
> +front.shopping.not_purchase_product_class: '「%product%」は現時点で購入できません。該当商品をカートから削除しました。'
@dk-umebius 
messages.en.yamlへも追加お願いします。

2021-11-18 03:45 UTC, dk-umebius commented
@chihiro-adachi 
> @dk-umebius prありがとうございます。 ユニットテストがおちているのでご確認お願いできますでしょうか。 https://github.com/EC-CUBE/ec-cube/runs/4185787650?check_suite_focus=true

かしこまりました。追加でPRさせていただきます。
ぱっと見、4系でdtb_product_classテーブルのidが1から始まるようになってid=1のレコードがvisibleではなくなったためな気がしています。

2021-11-24 01:57 UTC, dk-umebius commented on src/Eccube/Resource/locale/messages.ja.yaml
> +front.shopping.not_purchase_product_class: '「%product%」は現時点で購入できません。該当商品をカートから削除しました。'
追加させていただきました。

2021-11-24 01:59 UTC, dk-umebius commented
> @dk-umebius prありがとうございます。 ユニットテストがおちているのでご確認お願いできますでしょうか。 https://github.com/EC-CUBE/ec-cube/runs/4185787650?check_suite_focus=true

@chihiro-adachi 
追加でコミットさせていただきました。

2021-11-29 00:27 UTC, chihiro-adachi approved these changes

2021-11-29 00:42 UTC, merged

2021-11-29 00:42 UTC, chihiro-adachi commented
@dk-umebius 
ありがとうございます。マージしました。