商品詳細画面のスキャンを追加
EC-CUBE/ec-cube pull request #5287
Opened 2022-02-01 01:47 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-02-01 02:07 UTC, nanasess requested changes

2022-02-01 02:07 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/front_guest/product_detail.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/front_guest_contact', true);
```suggestion
    await zapClient.newSession('/zap/wrk/sessions/front_guest_product_detail', true);
```
セッションのファイル名も変更お願いします

2022-03-03 02:17 UTC, nanasess approved these changes

2022-03-11 06:59 UTC, carkn commented
確認しました。問題ないかと思います。
マージします。

2022-03-11 07:00 UTC, merged