ZAP シナリオ 当サイトについてを追加
EC-CUBE/ec-cube pull request #5288
Opened 2022-02-01 06:50 UTC by carkn

## 概要(Overview・Refs Issue)
owasp zapのテストコードを追加しました。
当サイトについてのページを対象にしています。

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)
- 手元の環境で実行できることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-02-01 06:52 UTC, nanasess approved these changes

2022-02-01 06:57 UTC, nanasess commented
@carkn matrix.group への追加もお願いします
https://github.com/EC-CUBE/ec-cube/blob/a446f03f8287ee923b4da99cf4926ed7b2257939/.github/workflows/penetration-test.yml#L14-L17

2022-02-01 07:39 UTC, carkn commented
@nanasess 
ご指摘ありがとうございます。追加しました。

2022-03-11 06:34 UTC, chihiro-adachi requested changes

2022-03-11 06:34 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/front_guest/about.test.ts
> +test.describe.serial('サイトについてのテストをします', () => {
当サイトについて

2022-03-11 06:34 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/front_guest/about.test.ts
> +  test('お問い合わせページを表示します', async () => {
当サイトについて

2022-03-11 06:45 UTC, chihiro-adachi approved these changes

2022-03-11 06:45 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/front_guest/about.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/front_about', true);
front_guses_about

2022-03-25 06:36 UTC, merged

2022-03-25 06:36 UTC, chihiro-adachi commented
@carkn 
ありがとうございます。マージしました。