[WIP] Owasp ZAP レイアウトの削除
EC-CUBE/ec-cube pull request #5311
Opened 2022-02-24 04:25 UTC by matsuoshi

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-02-28 01:53 UTC, nanasess requested changes
いくつかコメント入れましたのでご確認お願いします

2022-02-28 01:53 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/content_layout_delete.test.ts
> +      page.click('.c-conversionArea .btn-ec-conversion')
以下の方が視認性が良いと思います
```suggestion
      page.click('.c-conversionArea >> text=登録')
```

2022-02-28 01:53 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/content_layout_delete.test.ts
> +import { ZapClient, Mode, ContextType, Risk, HttpMessage } from '../../utils/ZapClient';
`deleteButton` の型をインポートします
```suggestion
import { ZapClient, Mode, ContextType, Risk, HttpMessage, Locator } from '../../utils/ZapClient';
```

2022-02-28 01:53 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/content_layout_delete.test.ts
> +  let deleteButton = null
型指定した方がよさそうです
```suggestion
  let deleteButton: Locator;
```

2022-02-28 01:53 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/content_layout_delete.test.ts
> +      const messages = await zapClient.getMessages(url, await zapClient.getNumberOfMessages(url), 1);
`await zapClient.getLastMessage(url)` で良さそうです

2022-02-28 02:27 UTC, matsuoshi commented on zap/selenium/ci/TypeScript/test/admin/content_layout_delete.test.ts
> +      const messages = await zapClient.getMessages(url, await zapClient.getNumberOfMessages(url), 1);
こちら、最後に一覧ベージにGETアクセスしていたので `getLastMessage()` では取得できないようで、いったんこのままにしています

2022-02-28 02:27 UTC, matsuoshi commented on zap/selenium/ci/TypeScript/test/admin/content_layout_delete.test.ts
> +      page.click('.c-conversionArea .btn-ec-conversion')
ありがとうございます、 `>>` の記法知りませんでした！

2022-02-28 02:29 UTC, matsuoshi commented
@nanasess コメントありがとうございます、ご指摘反映しました

2022-02-28 02:53 UTC, nanasess approved these changes

2022-03-11 08:30 UTC, carkn commented
確認しました。問題ないかと思います。
マージします。

2022-03-16 10:30 UTC, merged