OWASP ZAP用シナリオ 商品CSV登録 雛形ダウンロードを追加
EC-CUBE/ec-cube pull request #5312
Opened 2022-02-24 04:55 UTC by carkn

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)
- 手元の環境で実行できることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-02-28 02:17 UTC, nanasess approved these changes

2022-03-25 06:55 UTC, chihiro-adachi requested changes

2022-03-25 06:55 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/admin/product_csv_template.test.ts
> +      scanId = await zapClient.activeScanAsUser(url, 2, 55, false, null, 'GET');
@carkn 
スキャン対象はproductURLになるかと思います。

2022-03-28 01:07 UTC, carkn commented on zap/selenium/ci/TypeScript/test/admin/product_csv_template.test.ts
> +      scanId = await zapClient.activeScanAsUser(url, 2, 55, false, null, 'GET');
@chihiro-adachi 
page.onではダウンロードができないことに気付きまして、流れ自体を修正しました。
訂正したものをアップしております。

2022-04-01 06:13 UTC, merged

2022-04-01 06:13 UTC, chihiro-adachi commented
@carkn 
ありがとうございます、マージしました。