商品CSV登録 販売制限数、通常価格の未指定の場合を追加
EC-CUBE/ec-cube pull request #5316
Opened 2022-03-02 09:26 UTC by watarukashii

## 概要(Overview・Refs Issue)

エンド様より、商品CSV登録の際、販売制限数および通常価格を未指定の場合、空で更新したいとのリクエストがあり回収しました。
今までは、未指定の場合は未更新でしたがこれからは空でアップデートされます。

## 方針(Policy)

他の項目に沿う形で改修しました。（ex. 商品コード）

## 実装に関する補足(Appendix)

説明も追記したほうが良いかと思い合わせて修正しております。

## テスト（Test)

## 相談（Discussion）

説明文の内容に問題がないかどうか相談したいです。

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更はありません
- [x] フックポイントの呼び出しタイミングの変更はありません
- [x] フックポイントのパラメータの削除・データ型の変更はありません
- [x] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [x] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-09 04:56 UTC, chihiro-adachi requested changes

2022-03-09 04:56 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Product/CsvImportController.php
> +        } else {
@watarukashii 
この場合、販売制限数の列自体がない場合に、すべて空更新になってしまうのであまり適切でないかもしれません。
列はあるが空欄の場合に更新する、でどうでしょうか。

2022-03-11 02:31 UTC, watarukashii commented on src/Eccube/Controller/Admin/Product/CsvImportController.php
> +        } else {
@chihiro-adachi コメントいただきありがとうございます。

> 列はあるが空欄の場合に更新する、でどうでしょうか。

こちらで進行いたします。PR贈りますのでご確認の程よろしくおねがいします。ありがとうございます。

2022-04-04 00:20 UTC, chihiro-adachi commented
@watarukashii 
ありがとうございます、修正確認しました。

2022-04-04 00:20 UTC, chihiro-adachi approved these changes

2022-04-04 00:21 UTC, merged