[WIP] E2E: EA07_BasicInformation
EC-CUBE/ec-cube pull request #5321
Opened 2022-03-09 09:19 UTC by matsuoshi

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-16 11:26 UTC, kiy0taka requested changes

2022-03-16 11:26 UTC, kiy0taka commented on codeception/acceptance/EA07BasicinfoCest.php
> +        $I->closeTab();
タブを閉じただけではセッションCookieは破棄されないので、「次回から自動的にログインする」のチェックを入れなくてもログイン状態は保持されています。
Codeceptionでブラウザを開き直すテストは実行できないので、以下のようにRememberMe Cookieがあるかを判定するだけでいいかと思います。
```
$I->seeCookie('eccube_remember_me');
```

2022-03-17 00:54 UTC, matsuoshi commented on codeception/acceptance/EA07BasicinfoCest.php
> +        $I->closeTab();
@kiy0taka ありがとうございます、 `$I->seeCookie()` で判定するよう、修正しました

2022-03-17 01:07 UTC, kiy0taka approved these changes

2022-03-17 06:38 UTC, merged