[OWASP ZAP]会員管理 会員一覧を追加
EC-CUBE/ec-cube pull request #5328
Opened 2022-03-17 08:38 UTC by carkn

## 概要(Overview・Refs Issue)
OWASP ZAPのテストコードを追加しました。
会員管理 会員一覧のページを対象にしています。

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)
- 手元の環境で実行できることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-18 07:02 UTC, nanasess requested changes

2022-03-18 07:02 UTC, nanasess commented on .github/workflows/penetration-test.yml
> -          - 'test/admin/content_layout_delete.test.ts'
以下が削除されてしまっているようです。ご確認お願いいたします
- 'test/admin/content_layout.test.ts'
- 'test/admin/content_layout_delete.test.ts'

2022-03-18 08:29 UTC, carkn commented on .github/workflows/penetration-test.yml
> -          - 'test/admin/content_layout_delete.test.ts'
@nanasess 
ご指摘ありがとうございます。
修正しました。

2022-03-22 00:38 UTC, nanasess approved these changes

2022-04-01 05:56 UTC, chihiro-adachi requested changes

2022-04-01 05:56 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/admin/customer.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/admin_index', true);
@carkn 
admin_index -> admin_customer

2022-04-01 06:45 UTC, carkn commented on zap/selenium/ci/TypeScript/test/admin/customer.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/admin_index', true);
@chihiro-adachi 
ありがとうございます。
訂正しました。

2022-04-22 00:26 UTC, chihiro-adachi approved these changes

2022-04-22 07:08 UTC, merged