[OWASP ZAP] 会員管理 会員登録
EC-CUBE/ec-cube pull request #5330
Opened 2022-03-18 09:38 UTC by carkn

## 概要(Overview・Refs Issue)
Owasp ZAP 自動化: 管理画面 > 会員管理 会員登録 > 新規登録

## 方針(Policy)

## 実装に関する補足(Appendix)
登録が実際に行われないようにするため、パッチを作成しました。

## テスト（Test)
手元の環境で動作確認を行っています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-28 01:37 UTC, nanasess requested changes

2022-03-28 01:37 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/customer_new.test.ts
> +    await page.fill('[placeholder="例：ec-cube\\@example\\.com"]', 'taro_yamada@test.local');
メールアドレスが固定されているため、 常に **このメールアドレスは利用できません** というエラーになってしまうようです。
`entityManager->flush()` を抑制するパッチを当てる必要がありそうですが、いかがでしょうか。

2022-03-28 01:37 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/customer_new.test.ts
> +    await page.click('button:has-text("登録")');
```suggestion
    await page.click('button >> text=登録');
 ```
で、いかがでしょうか？

2022-03-28 01:37 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/customer_new.test.ts
> +  test('ユーザ情報を入力します', async () => {
エスケープ文字 `\\` で煩雑な記述になっているため、ID 指定の方がシンプルに記述できそうですが、いかがでしょう？

2022-04-01 07:58 UTC, carkn commented
@nanasess 
ご確認ありがとうございます。
諸々修正させていただきました。

2022-04-01 08:03 UTC, nanasess approved these changes

2022-05-19 23:55 UTC, merged