[OWASP ZAP] キャッシュ管理
EC-CUBE/ec-cube pull request #5331
Opened 2022-03-19 16:07 UTC by carkn

## 概要(Overview・Refs Issue)
OWASP ZAP 自動化: 管理画面 コンテンツ管理 -> キャッシュ管理を追加

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)
手元の環境で実行できることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-22 00:40 UTC, nanasess approved these changes

2022-04-01 05:59 UTC, chihiro-adachi requested changes

2022-04-01 05:59 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/admin/content_cache.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/admin_contact_cache', true);
@carkn 
admin_contact_cache -> admin_content_cache

2022-04-01 08:02 UTC, carkn commented on zap/selenium/ci/TypeScript/test/admin/content_cache.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/admin_contact_cache', true);
@chihiro-adachi 
ありがとうございます。訂正させていただきました。

2022-04-22 00:25 UTC, chihiro-adachi approved these changes

2022-04-22 00:25 UTC, merged