【OWASP ZAP】管理画面＞商品管理＞商品一覧のテストを追加
EC-CUBE/ec-cube pull request #5332
Opened 2022-03-23 03:21 UTC by kurozumi

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-28 01:08 UTC, nanasess approved these changes

2022-04-01 06:36 UTC, chihiro-adachi requested changes

2022-04-01 06:36 UTC, chihiro-adachi commented on zap/selenium/ci/TypeScript/test/admin/product.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/admin_index', true);
@kurozumi 
セッション名は以下でお願いします。
admin_index -> admin_product

2022-04-04 00:56 UTC, kurozumi commented on zap/selenium/ci/TypeScript/test/admin/product.test.ts
> +    await zapClient.newSession('/zap/wrk/sessions/admin_index', true);
修正しました。

2022-04-21 08:13 UTC, chihiro-adachi approved these changes

2022-04-21 08:14 UTC, merged

2022-04-21 08:14 UTC, chihiro-adachi commented
@kurozumi ありがとうございます、マージしました