[OWASP ZAP] 会員管理 会員情報編集
EC-CUBE/ec-cube pull request #5333
Opened 2022-03-23 09:35 UTC by carkn

## 概要(Overview・Refs Issue)
Owasp ZAP 自動化: 管理画面 会員情報 → 編集
についてのテストを追加

## 方針(Policy)

## 実装に関する補足(Appendix)
実際に編集が行われないようにパッチを作成しています。

## テスト（Test)
手元の環境で実行できることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-30 08:35 UTC, nanasess requested changes

2022-03-30 08:35 UTC, nanasess commented on .github/workflows/penetration-test.yml
> +      - name: Apply patch to edit_customer
更新の場合は commit されても重複エラーになったりすることは無いのでパッチ不要かと思いますがいかがでしょう？

2022-04-01 08:15 UTC, carkn commented on .github/workflows/penetration-test.yml
> +      - name: Apply patch to edit_customer
@nanasess 
ありがとうございます。
パッチを取り下げさせて頂きました。

2022-04-01 08:16 UTC, carkn commented
会員情報の入力でエスケープ文字(//)を使用していた記述を変更しました。

2022-04-08 02:10 UTC, nanasess approved these changes

2022-04-21 08:13 UTC, merged