Zap admin product class name
EC-CUBE/ec-cube pull request #5334
Opened 2022-03-24 10:18 UTC by carkn

## 概要(Overview・Refs Issue)
Owasp ZAP 自動化: 商品管理 > 規格管理 新規追加
についてのテストを追加

## 方針(Policy)

## 実装に関する補足(Appendix)
実際に新規追加が行われないようにパッチを作成しています。

## テスト（Test)
手元の環境で実行できることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-28 01:40 UTC, nanasess requested changes

2022-03-28 01:40 UTC, nanasess commented on .github/workflows/penetration-test.yml
> +      - name: Apply patch to new_product_class_name
規格の新規登録時は重複チェックしないため、パッチを当てなくてもテストできそうですが、いかがでしょうか？

2022-04-01 08:18 UTC, carkn commented on .github/workflows/penetration-test.yml
> +      - name: Apply patch to new_product_class_name
@nanasess 
ご指摘ありがとうございます。
パッチ適用を取り下げさせていただきました。

2022-04-08 02:12 UTC, nanasess approved these changes

2022-04-21 08:12 UTC, merged