[OWASP ZAP] 商品管理>カテゴリ管理 CSVダウンロードを追加
EC-CUBE/ec-cube pull request #5337
Opened 2022-03-28 04:42 UTC by carkn

## 概要(Overview・Refs Issue)
OWASP ZAP 商品管理>カテゴリ管理 CSVダウンロードを追加

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)
手元の環境で実行できていることを確認しています。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-03-30 08:32 UTC, nanasess requested changes

2022-03-30 08:32 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/product_category_export.test.ts
> +  const ｃｓｖExportURL = `${PlaywrightConfig.use.baseURL}/${ECCUBE_ADMIN_ROUTE}/product/category/export`;
CSV が全角のようですが、意図的でしょうか？

2022-03-30 08:32 UTC, nanasess commented on zap/selenium/ci/TypeScript/test/admin/product_category_export.test.ts
> +      scanId = await zapClient.activeScanAsUser(ｃｓｖExportURL, 2, 55, false, null, 'GET', message.requestBody);
GET の場合は requestBody 不要かと思います

2022-04-01 08:29 UTC, carkn commented on zap/selenium/ci/TypeScript/test/admin/product_category_export.test.ts
> +  const ｃｓｖExportURL = `${PlaywrightConfig.use.baseURL}/${ECCUBE_ADMIN_ROUTE}/product/category/export`;
@nanasess 
ご指摘ありがとうございます。
修正しました。

2022-04-01 08:30 UTC, carkn commented on zap/selenium/ci/TypeScript/test/admin/product_category_export.test.ts
> +      scanId = await zapClient.activeScanAsUser(ｃｓｖExportURL, 2, 55, false, null, 'GET', message.requestBody);
@nanasess 
ご指摘ありがとうございます。
削除させていただきました。

2022-04-08 02:11 UTC, nanasess approved these changes

2022-04-21 06:52 UTC, merged

2022-04-21 06:52 UTC, chihiro-adachi commented
@carkn 
ありがとうございます、マージしました