注文手続でフォームエラーが返ると fatal error となる不具合を修正
EC-CUBE/ec-cube pull request #5345
Opened 2022-04-06 04:08 UTC by pineray

## 概要(Overview・Refs Issue)
注文手続きのフォームでエラーが返ると fatal error となる。
ShoppingController の confirm アクションでは、フォームエラーの場合にテンプレートを差し替えてフォームを表示するよう意図されているが、パラメーターが不十分なためにエラーとなっている。

## 方針(Policy)
エラーとなっている箇所で必要とされているパラメーターを、テンプレート差し替えの際に提供する。

## 実装に関する補足(Appendix)
注文手続きで「お問い合わせ」欄に3,001文字以上入力して送信すると再現できます。

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-04-06 04:59 UTC, chihiro-adachi commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
@pineray 
このownerパラメータってなんですか？
ドキュメント等あれば教えていただければと。

2022-04-06 05:22 UTC, pineray commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
@chihiro-adachi 
そのテンプレートがどのコントローラーのアクションから呼び出されているかを示すもののようです。
$request の attributes パラメーターに直接セットすることが一般的な使い方ではないようで、ざっと探してみてもドキュメントが見当たりません

2022-04-06 08:18 UTC, chihiro-adachi commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
なるほど。ありがとうございます。

2022-04-06 08:33 UTC, kiy0taka commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
処理によってテンプレートを変えるなら `@Template` 使わずに、[render](https://symfony.com/doc/4.4/controller.html#rendering-templates) メソッド使う方法でいいかと思います。

2022-04-08 07:07 UTC, chihiro-adachi commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
@kiy0taka 
renderメソッドだとtemplate eventが発動しないため、無理やり@Templateを使っているんだと思います

2022-04-13 04:52 UTC, kiy0taka commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
なるほど。。

2022-04-13 23:29 UTC, chihiro-adachi commented
@pineray 
注文手続きで3001文字以上入力し、確認するボタンをクリックで以下の状態になりました。
システムエラーは発生しなかったのですが再現手順は他に何か必要でしょうか？
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/8196725/163285945-f755d011-a5ba-4712-951d-039122c2b867.png">

2022-04-14 04:12 UTC, pineray commented
@chihiro-adachi 
WSL2 の Ubuntu 上でレポジトリの最新状態にしてから、docker compose でイメージを新しく作成してインストールした直後に、注文手続きで3001文字入力して確認ボタンを押すと、やはり fatal error となります。
何が違っているのだろう
![Screenshot 2022-04-14 at 12-59-28 Notice Undefined offset 0 (500 Internal Server Error)](https://user-images.githubusercontent.com/558669/163312174-a78bf34f-1915-426e-ae95-68e4f7abd2ee.png)

2022-04-14 04:46 UTC, nanasess commented
`APP_ENV=dev` だからじゃないですかね

2022-04-18 06:36 UTC, pineray commented
docker-compose.yml の  APP_ENV を prod に変更して同じ操作を行うと、「システムエラーが発生しました」と表示されます
![Screenshot 2022-04-18 at 15-29-47 システムエラーが発生しました。](https://user-images.githubusercontent.com/558669/163766248-205f2705-4e94-4c05-bc66-d894f13ac88e.png)

2022-04-21 00:42 UTC, chihiro-adachi commented
@pineray 
すみません、cloneし直してdocker-composeで起動したところ再現しました。

2022-04-21 00:51 UTC, chihiro-adachi requested changes

2022-04-21 00:51 UTC, chihiro-adachi commented on src/Eccube/Controller/ShoppingController.php
> +            'owner' => [self::class, 'confirm'],
@pineray 
ownerパラメータですが、利用箇所を追ってみると、\ReflectionObjectに渡されていました。
`self::class`ではなく、`$this`オブジェクトで渡してあげるのが良さそうです。
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/7fd1d54c1b27f094a68ae15a99b7fc815857255f/src/EventListener/TemplateListener.php#L99
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/7fd1d54c1b27f094a68ae15a99b7fc815857255f/src/EventListener/TemplateListener.php#L144

2022-05-13 03:35 UTC, chihiro-adachi approved these changes

2022-05-18 07:49 UTC, merged

2022-05-18 07:50 UTC, chihiro-adachi commented
@pineray 
ありがとうございます。マージしました。