インボイス対応
EC-CUBE/ec-cube pull request #5382
Opened 2022-06-06 09:16 UTC by nanasess

## 概要(Overview・Refs Issue)

- #4268 
- インボイス制度に準拠するよう消費税額の表示方法を修正

## 方針(Policy)

- 以下、 issues の方針に準拠するよう修正
  - https://github.com/EC-CUBE/ec-cube/issues/4268#issuecomment-1144531814 

## 実装に関する補足(Appendix)

## テスト（Test)

以下計算例と同様のユニットテストを追加
https://github.com/EC-CUBE/ec-cube/issues/4268#issuecomment-1144531814

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-06-21 07:22 UTC, chihiro-adachi requested changes

2022-06-21 07:22 UTC, chihiro-adachi commented on src/Eccube/Entity/BaseInfo.php
> +         * @ORM\Column(name="invoice_registration_number", type="string", length=4000, nullable=true)
登録番号はT+13桁 or T+法人番号のようなので、length=255で十分かと思いました。

2022-06-21 07:22 UTC, chihiro-adachi commented on src/Eccube/Form/Type/Admin/ShopMasterType.php
> +                'required' => false
Assert\Lengthでバリデーションお願いします。

2022-06-21 07:23 UTC, chihiro-adachi commented
@nanasess 
マイページも修正必要かもです。
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/8196725/174740524-d4a89208-8b69-44b3-b6ce-b9d06a471b04.png">

2022-06-21 08:13 UTC, nanasess commented on src/Eccube/Entity/BaseInfo.php
> +         * @ORM\Column(name="invoice_registration_number", type="string", length=4000, nullable=true)
length=255 に修正しました

2022-06-21 08:13 UTC, nanasess commented on src/Eccube/Form/Type/Admin/ShopMasterType.php
> +                'required' => false
バリデーション追加しました

2022-06-21 08:14 UTC, nanasess commented
@chihiro-adachi マイページも対応しました

2022-06-22 00:04 UTC, chihiro-adachi commented
@nanasess 
修正ありがとうございます。

1点質問なのですが端数処理ってどこで実行されてます？
実装箇所がぱっとみあたらずでして。。

2022-06-22 00:28 UTC, nanasess commented
@chihiro-adachi コードを整理したときに処理がぬけてしまったみたいです。。。
確認しますので少々おまちください

2022-06-22 05:33 UTC, nanasess commented
@chihiro-adachi 処理追加しました

2022-06-23 07:41 UTC, chihiro-adachi commented
@nanasess 
ありがとうございます。修正確認しました。

一点懸念として、dtb_order_itemのデータ構造上、同一税率であっても課税規則は異なるものを持つことは可能です。
ただ、レアケースかと思いましたので、仕様ということで扱いたいと思います。
もしそのようなデータができた場合は、dtb_order_item.rounding_type_idの値をデータ修正してもらうことで解消可能です。

2022-06-23 07:41 UTC, merged