認証キー発行処理をcookieに依存しない実装に変更
EC-CUBE/ec-cube pull request #5388
Opened 2022-06-14 00:15 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

#4416

## 方針(Policy)

キャプチャ文字列の保持をセッションを使って実装していたが、セッションCookieがサードパーティーCookieとなるためsafariで動作していなかった。

package-api側をCookieに依存しない実装に変更し、クライアントであるEC-CUBE側もそれに合わせて追随

## 実装に関する補足(Appendix)

キャプチャ画像リクエスト時に、x-eccube-captcha-idというレスポンスヘッダが返されます。
認証キー発行リクエスト時にx-eccube-captcha-idの値とキャプチャ文字列をセットで渡すことで、キャプチャ文字列の照合を行います。

## テスト（Test)

以下ブラウザで動作することを確認しています。

- safari
- chrome のシークレットモード

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-06-14 07:59 UTC, kiy0taka requested changes
`XMLHttpRequest` を使用している理由は何かありますか？
とくにないのであればjQueryを使用したほうがいいです。

2022-06-15 03:53 UTC, chihiro-adachi commented
@kiy0taka 
jqueryだとバイナリの取得に難があり`XMLHttpRequest `で代替としています。
https://qiita.com/tom_konda/items/484955b8332e0305ebc4
https://qiita.com/yuma84/items/fefb95c1a10396070cd2

2022-06-15 04:27 UTC, kiy0taka approved these changes

2022-06-15 04:27 UTC, kiy0taka commented
なるほど。理解しました。

2022-06-23 08:12 UTC, merged