[4.2] jQuery-File-Upload を filepond に変更する
EC-CUBE/ec-cube pull request #5395
Opened 2022-06-17 08:19 UTC by nanasess

## 概要(Overview・Refs Issue)

- #5383 
- #5385 
- jQuery-File-Upload が開発終了しているため、 [filepond](https://github.com/pqina/filepond/) に変更する

## 方針(Policy)

- 画像アップロードを使用している機能(商品管理、お支払い方法管理)を filepond の実装に変更する

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-06-27 02:20 UTC, chihiro-adachi commented
@nanasess 
こちらコンフリクト解消おねがいできますでしょうか。

2022-06-27 03:48 UTC, nanasess commented
@chihiro-adachi コンフリクト解消しました。 npm install が動作しなくなったため #5389 の修正も取り込みました

2022-06-27 06:18 UTC, chihiro-adachi requested changes

2022-06-27 06:18 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +     * @deprecated jQuery-File-Upload で利用していたメソッドのため非推奨
@nanasess 
ファイルアップロードのメソッドを残すのはリスクが高そうなので、非推奨ではなく削除でよいかと思いました。

2022-06-27 06:18 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +        if (file_exists($image) && stripos(realpath($image), $this->getParameter('kernel.project_dir')) === 0) {
@nanasess 
パストラバーサルできてしまうので確認お願いします。

```
function reqListener () {
  console.log(this.responseText);
}

var req = new XMLHttpRequest();
req.addEventListener("load", reqListener);
req.open("GET", "http://127.0.0.1:8000/admin/setting/shop/payment/image/load?source=/.env");
req.send();
```

2022-06-27 06:25 UTC, chihiro-adachi commented
アップロードのエリアをはみ出してしまう

<img width="680" alt="image" src="https://user-images.githubusercontent.com/8196725/175873109-28ee5777-6ba3-4489-aace-e62ad5cca029.png">

2022-06-27 23:37 UTC, chihiro-adachi commented
@nanasess 
PaymentContoroller::imageAddも削除お願いします。

2022-06-28 00:30 UTC, nanasess commented
@chihiro-adachi すみません、削除しました

2022-06-28 02:48 UTC, chihiro-adachi commented
@nanasess 
UnitTestが落ちているようですので（おそらくこちらも削除必要かと）ご確認お願いします。

2022-06-28 02:56 UTC, nanasess commented
@chihiro-adachi テストも削除しました

2022-06-28 05:27 UTC, chihiro-adachi approved these changes

2022-06-28 09:56 UTC, kiy0taka requested changes

2022-06-28 09:56 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->getParameter('kernel.project_dir')) === 0) {
相対パスで、`kernel.project_dir` 以下の任意のファイルが削除できてしまうので `eccube_temp_image_dir` 以下かどうかのチェックに変更お願いします。
temp_dirかsave_dir以下のチェックが散在しているので、メソッド化した方がいいかもしれません。

2022-06-28 09:56 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->getParameter('kernel.project_dir')) === 0) {
こちらも対応お願いします。

2022-06-28 10:08 UTC, nanasess commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->getParameter('kernel.project_dir')) === 0) {
`eccube_temp_image_dir` に修正しました

2022-06-28 10:09 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->getParameter('kernel.project_dir')) === 0) {
こちらも修正しました

2022-06-29 00:00 UTC, kiy0taka approved these changes

2022-06-29 00:02 UTC, kiy0taka requested changes

2022-06-29 00:02 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->eccubeConfig['eccube_temp_image_dir']) === 0) {
リクエストボディを空で送ると `eccube_temp_image_dir` ディレクトリが削除さてしまうので、ファイルかどうかのチェックもお願いします。

2022-06-29 00:02 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->eccubeConfig['eccube_temp_image_dir']) === 0) {
こちらも対応お願いします。

2022-06-29 00:16 UTC, nanasess commented on src/Eccube/Controller/Admin/Product/ProductController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->eccubeConfig['eccube_temp_image_dir']) === 0) {
`file_exists()` ではなく `is_file()` に変更してみました

2022-06-29 00:16 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
> +        if (file_exists($tempFile) && stripos(realpath($tempFile), $this->eccubeConfig['eccube_temp_image_dir']) === 0) {
こちらも修正しました

2022-06-29 00:18 UTC, kiy0taka approved these changes

2022-06-29 06:00 UTC, merged

2022-06-29 06:01 UTC, chihiro-adachi commented
@nanasess 
ご対応ありがとうございました！