Issue/5304
EC-CUBE/ec-cube pull request #5399
Opened 2022-06-20 06:12 UTC by sai-gillingham

## 概要(Overview・Refs Issue)
[#5304]
改正商取引法の施行に伴うECカート「最終確認画面」表示項目の変更

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-06-27 02:43 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/TradeLawController.php
> +    private TradeLawRepository $tradeLawRepository;
他の Controller に合わせて protected でお願いします

2022-06-27 02:44 UTC, nanasess requested changes

2022-06-27 02:44 UTC, nanasess commented on src/Eccube/Controller/ShoppingController.php
> +    private TradeLawRepository $tradeLawRepository;
他の Controller に合わせて protected でお願いします

2022-06-27 08:42 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/TradeLawController.php
> +    private TradeLawRepository $tradeLawRepository;
```suggestion
    protected TradeLawRepository $tradeLawRepository;
```

2022-06-27 09:00 UTC, nanasess requested changes
Add suggestions

2022-06-27 09:00 UTC, nanasess commented on src/Eccube/Controller/ShoppingController.php
> +    private TradeLawRepository $tradeLawRepository;
```suggestion
    protected TradeLawRepository $tradeLawRepository;
```

2022-06-27 09:00 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/TradeLawController.php
> +     * 税率設定の初期表示・登録
```suggestion
     * 特定商取引法設定の初期表示・登録
```

2022-06-27 09:00 UTC, nanasess commented on src/Eccube/Controller/Admin/Setting/Shop/TradeLawController.php
> +                $this->entityManager->persist($OrderStatus);
```suggestion
                $TradeLaw = $child->getData();
                $this->entityManager->persist($TradeLaw);
```

2022-06-27 09:00 UTC, nanasess commented on tests/Eccube/Tests/Web/ShoppingControllerTest.php
> +        $this->entityManager->flush();
```suggestion
        $this->entityManager->flush();
```

2022-06-27 09:00 UTC, nanasess commented on tests/Eccube/Tests/Web/ShoppingControllerTest.php
> +        $this->entityManager->flush();
```suggestion
        $this->entityManager->flush();
```

2022-06-27 09:03 UTC, nanasess requested changes
add suggestions

2022-06-27 09:03 UTC, nanasess commented on tests/Eccube/Tests/Web/Admin/Setting/Shop/TradeLawControllerTest.php
> +        var_dump($responseCrawler->outerHtml());
```suggestion
        $editedToggle = $responseCrawler->filter('#form_TradeLaws_10_displayOrderScreen');
```

2022-06-28 02:14 UTC, sai-gillingham commented on src/Eccube/Controller/Admin/Setting/Shop/TradeLawController.php
> +     * 税率設定の初期表示・登録
コメントありがとうございます。こちらのコメントを更新しました。

2022-06-28 02:15 UTC, sai-gillingham commented on src/Eccube/Controller/Admin/Setting/Shop/TradeLawController.php
> +                $this->entityManager->persist($OrderStatus);
コメントありがとうございます。変数名を更新しました。

2022-06-28 02:23 UTC, sai-gillingham commented on tests/Eccube/Tests/Web/ShoppingControllerTest.php
> +        $this->entityManager->flush();
ありがとうございます。重複flush()コールを削除しました。

2022-06-28 02:25 UTC, sai-gillingham commented on tests/Eccube/Tests/Web/ShoppingControllerTest.php
> +        $this->entityManager->flush();
コメントありがとうございます。重複flush()コールを削除しました。

2022-06-28 02:30 UTC, sai-gillingham commented on tests/Eccube/Tests/Web/Admin/Setting/Shop/TradeLawControllerTest.php
> +        var_dump($responseCrawler->outerHtml());
コメントありがとうございます。var_dump()を残してすみません。var_dump()を削除しました。

2022-06-28 02:38 UTC, sai-gillingham commented on src/Eccube/Controller/ShoppingController.php
> +    private TradeLawRepository $tradeLawRepository;
了解いたしました。他の変数と合わせて変数定義 [例 TradeLawRepository] を削除した方が良いでしょうか？

2022-06-28 02:50 UTC, sai-gillingham commented on src/Eccube/Controller/ShoppingController.php
> +    private TradeLawRepository $tradeLawRepository;
```suggestion
    private $tradeLawRepository;
```

2022-06-28 03:03 UTC, sai-gillingham commented on src/Eccube/Controller/ShoppingController.php
> +    private TradeLawRepository $tradeLawRepository;
コメントありがとうございます。protected に更新しました。

2022-06-28 04:51 UTC, nanasess commented
@sai-gillingham ご対応ありがとうございます！ SQLite3 でテストが落ちていたので修正したのと、フロント側の特定商取引法のページを追加しました

2022-06-28 04:51 UTC, nanasess approved these changes

2022-06-29 08:58 UTC, merged

2022-06-29 08:58 UTC, chihiro-adachi commented
@sai-gillingham 
ご対応ありがとうございます。マージしました。