fix issue/5252 - CSVインポート時にデリミタがエスケープされていることがある
EC-CUBE/ec-cube pull request #5407
Opened 2022-06-24 10:46 UTC by tpsnghiale

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-06-28 07:44 UTC, nanasess approved these changes

2022-06-28 09:33 UTC, nanasess requested changes
ロケールの関係？で、正しく CSV ファイルをパースできなくなる模様。列が欠落したりするため要調査

2022-07-11 03:31 UTC, nanasess commented
> ロケールの関係？で、正しく CSV ファイルをパースできなくなる模様。列が欠落したりするため要調査

`SplFileObject::READ_CSV` が SJIS に対応していないため、正常にパースできない。
2系のように、 `stream_filter` を使用することで実現できるかもしれない
https://github.com/EC-CUBE/ec-cube2/blob/3129289ea4629337946609025cf3e3cb96436000/data/class/helper/SC_Helper_CSV.php#L380-L400

2022-07-12 06:48 UTC, nanasess approved these changes

2022-07-12 06:55 UTC, nanasess commented
stream filter を使用して変換することで対応しました。
また、 `AbstractCsvImportController` で処理していた改行コード変換も stream filter を使用するようにしました

2022-07-15 05:15 UTC, chihiro-adachi commented
@nanasess 
ありがとうございます。

こちらのCSV、商品CSV登録時にエラーとなりました。見ていただくことはできますでしょうか？
[product_20220715141042.csv](https://github.com/EC-CUBE/ec-cube/files/9118008/product_20220715141042.csv)

<img width="482" alt="image" src="https://user-images.githubusercontent.com/8196725/179155413-8d502ae8-7e0f-4bc0-b7d4-7e9c55293fe6.png">

2022-07-15 05:49 UTC, nanasess commented
@chihiro-adachi 

> こちらのCSV、商品CSV登録時にエラーとなりました。見ていただくことはできますでしょうか？
> [product_20220715141042.csv](https://github.com/EC-CUBE/ec-cube/files/9118008/product_20220715141042.csv)

このCSVファイルには商品IDの項目が無いためエラーになっていたようです。商品IDを追加したところ正常にアップロードできましたのでご確認ください

2022-07-15 06:42 UTC, chihiro-adachi commented
商品IDを追加したCSVでも同様のエラーとなりました。
ファイルを添付しておきます。

[product-sjis.csv](https://github.com/EC-CUBE/ec-cube/files/9118496/product-sjis.csv)
[product-utf-8.csv](https://github.com/EC-CUBE/ec-cube/files/9118495/product-utf-8.csv)

2022-07-15 08:56 UTC, nanasess commented
@chihiro-adachi stream filter に関係なく、 `$form['import_file']->getData()`  でデータを取り出した時点で以下のようにデータが壊れてしまう模様です。。。

```
商品ID,公開ステータス(ID),販売種別(ID),商品名,販売価格,在庫数,在庫数無制限フラグ
,1,1,"10テスト機構",2800,100,
,1,1,11テスト機構"",2800,100,
```

2022-07-18 23:56 UTC, chihiro-adachi commented
@nanasess 

ファイルを分割するタイミングで壊れてしまうようなので、分割前にフィルタかける必要がありそうです。

一応以下でうまくいきました。
https://github.com/chihiro-adachi/ec-cube/commit/0bf4a28bf919a9a99409de7dc10601ccf79b1974

2022-07-19 00:09 UTC, nanasess commented
@chihiro-adachi なるほど、ありがとうございます！

2022-07-19 07:56 UTC, nanasess commented
@chihiro-adachi いただいたコミットを取り込んでリファクタリングしました。これで大丈夫だと思います。

2022-07-19 22:48 UTC, chihiro-adachi commented
@nanasess 
ありがとうございます！
sjis.csv, utf-8.csvともに正常に登録できました。

2022-07-19 22:48 UTC, merged