モーダルの背景をクリックするとモーダルが消えてしまうのを修正
EC-CUBE/ec-cube pull request #5421
Opened 2022-07-06 07:22 UTC by nanasess

## 概要(Overview・Refs Issue)

プラグインインストール時のプログレスバーなど、画面を遷移させず待機する必要があるモーダルの背景をクリックすると、モーダルが解除されてしまうのを修正。
bootstrap5 対応時のデグレード

## 方針(Policy)

`data-backdrop` を `data-bs-backdrop` に修正

## 実装に関する補足(Appendix)

## テスト（Test)

モーダルが解除されないのを確認

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-07-07 01:28 UTC, chihiro-adachi requested changes

2022-07-07 01:28 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Order/index.twig
> -                <div class="modal fade" id="sentUpdateModal" tabindex="-1" role="dialog" aria-labelledby="sentUpdateModal" aria-hidden="true" data-keyboard="false" data-backdrop="static">
@nanasess 
`data-keyboard`も対応必要な気がします。
確認できてないですが、おそらくEscキーでモーダル消えるんじゃないかと。

2022-07-07 02:03 UTC, nanasess commented on src/Eccube/Resource/template/admin/Order/index.twig
> -                <div class="modal fade" id="sentUpdateModal" tabindex="-1" role="dialog" aria-labelledby="sentUpdateModal" aria-hidden="true" data-keyboard="false" data-backdrop="static">
ありがとうございます。 data-keyboard も対応しました

2022-07-11 23:57 UTC, chihiro-adachi approved these changes

2022-07-11 23:58 UTC, chihiro-adachi commented
ありがとうございます。修正確認しました

2022-07-11 23:58 UTC, merged