注文時に支払い方法が非表示に変更された場合エラーが発生するよう修正
EC-CUBE/ec-cube pull request #5558
Opened 2022-08-17 10:41 UTC by kurozumi

## 概要(Overview・Refs Issue)

以下のissueの対応です。
https://github.com/EC-CUBE/ec-cube/issues/5549

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-08-17 22:59 UTC, chihiro-adachi requested changes

2022-08-17 22:59 UTC, chihiro-adachi commented on src/Eccube/Service/PurchaseFlow/Processor/PaymentValidator.php
> +            if (false === $itemHolder->getPayment()->isVisible()) {
@kurozumi 
一部の決済プラグインや特定の条件によってはgetPayment()がnullを返すことがありますので、getPaymentのnullチェックをお願いできればありがたいです。

2022-08-18 00:06 UTC, kurozumi commented
@chihiro-adachi 
対応しました。

2022-08-18 01:30 UTC, chihiro-adachi commented
@kurozumi 
ご対応ありがとうございます！

2022-08-18 01:30 UTC, chihiro-adachi approved these changes

2022-08-18 01:56 UTC, merged