ref #5581
EC-CUBE/ec-cube pull request #5582
Opened 2022-08-20 01:38 UTC by nobuhiko

## 概要(Overview・Refs Issue)
#5581

## 方針(Policy)
https://getbootstrap.jp/docs/5.0/components/alerts/
書き方が少し変わったらしい

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-08-23 08:25 UTC, nanasess requested changes

2022-08-23 08:25 UTC, nanasess commented on src/Eccube/Resource/template/install/step1.twig
> +                            <div class="alert alert-danger alert-dismissable fade show" role="alert">
`alert-dismissible` が正しいと思います

```suggestion
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
```

2022-08-24 00:11 UTC, nanasess approved these changes

2022-08-24 03:58 UTC, chihiro-adachi commented
@nobuhiko 
ありがとうございます。修正確認しました。

2022-08-24 03:59 UTC, merged