管理者ログイン画面のID, PWの長さ制限をeccube.yamlの設定値にそろえる
EC-CUBE/ec-cube pull request #5621
Opened 2022-08-24 12:35 UTC by kazuyoshikakihara

## 概要(Overview・Refs Issue)

Form/Type/Admin/LoginType.php 内の login_id, password の長さ制限(maxlength)がハードコーディングされていました。
eccube.yaml 内でid, password の長さ制限値（eccube_id_max_len, eccube_password_max_len）を大きな値に変更した場合にログインできなくなる恐れがあるので、eccube.yaml の値をそのまま持ってくるように修正しました。

## テスト（Test)

もともと動作していた部分ですので、テストに手は加えていません

念のため、正しい id, password の組み合わせでログインできること、不正な id, password の組み合わせでログインできないことを目視確認してあります。

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更はありません
- [x] フックポイントの呼び出しタイミングの変更はありません
- [x] フックポイントのパラメータの削除・データ型の変更はありません
- [x] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [x] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-08-24 22:42 UTC, chihiro-adachi commented
@kazuyoshikakihara 
ありがとうございます。E2Eテストが落ちているようなのでご確認お願いできますでしょうか。

2022-08-27 05:03 UTC, kazuyoshikakihara commented
@chihiro-adachi 
#5613 に関連しそうなので
そちらに2件コメントさせていただきました。
https://github.com/EC-CUBE/ec-cube/issues/5613#issuecomment-1229118862
https://github.com/EC-CUBE/ec-cube/issues/5613#issuecomment-1229124116

今回のプルリクエストの問題ではないようです。

2022-08-31 20:53 UTC, chihiro-adachi requested changes

2022-08-31 20:53 UTC, chihiro-adachi commented on src/Eccube/Form/Type/Admin/LoginType.php
> +                'maxlength' => $this->eccubeConfig['eccube_password_max_len'],
@kazuyoshikakihara 
`eccube_password_max_len`はeccube.ymlでは`32`で定義されているようです。
eccube.ymlの値も`50`に更新お願いできますでしょうか。

2022-08-31 23:30 UTC, kazuyoshikakihara commented on src/Eccube/Form/Type/Admin/LoginType.php
> +                'maxlength' => $this->eccubeConfig['eccube_password_max_len'],
外部からは32か50かどちらが正しいのかわかりませんので、ご指示どおり50にします。

2022-09-01 10:24 UTC, chihiro-adachi commented on src/Eccube/Form/Type/Admin/LoginType.php
> +                'maxlength' => $this->eccubeConfig['eccube_password_max_len'],
@kazuyoshikakihara 
ご対応ありがとうございます。

> 外部からは32か50かどちらが正しいのかわかりませんので、ご指示どおり50にします。

どちらが正というわけではないですが、互換性の観点から大きい方に寄せることが多いです。

2022-09-01 10:24 UTC, chihiro-adachi approved these changes

2022-09-01 10:25 UTC, merged