voidのメソッドでリターンしているコードを修正
EC-CUBE/ec-cube pull request #5692
Opened 2022-08-29 09:28 UTC by takeuji

## 概要(Overview・Refs Issue)

voidのメソッドでリターンしているコードを修正しました
ちょうど、[#5578](https://github.com/EC-CUBE/ec-cube/pull/5578#issuecomment-1220614075)で修正済みのものもありました

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-08-29 22:29 UTC, chihiro-adachi requested changes

2022-08-29 22:29 UTC, chihiro-adachi commented on src/Eccube/Service/Composer/ComposerProcessService.php
> +        composerApiService->configureRepository($BaseInfo);
@takeuji 
ここでSyntax errorが発生してました。
`$this->`が抜けてるようです。

2022-08-29 22:29 UTC, chihiro-adachi commented on src/Eccube/Service/Composer/ComposerProcessService.php
> +        composerApiService->foreachRequires($packageName, $version, $callback, $typeFilter, $level);
同上

2022-08-31 08:09 UTC, takeuji commented
@chihiro-adachi 
すみません、、修正しました。

2022-08-31 22:08 UTC, chihiro-adachi approved these changes

2022-08-31 22:08 UTC, merged