以下のissue/5753の対応です
EC-CUBE/ec-cube pull request #5761
Opened 2022-09-01 09:14 UTC by maianhtu010596

## 概要(Overview・Refs Issue)

以下のissueの対応です。
[https://github.com/EC-CUBE/ec-cube/issues/5753](https://github.com/EC-CUBE/ec-cube/issues/5753) 受注編集の画面で、金額にエラーがあると、課税区分のカッコ内が表示されなくなる

問題を修正した後の結果は次のようになります。
![image](https://user-images.githubusercontent.com/105194449/187877238-e7e80106-a7c5-4c1f-9c5e-9cb90ebe0868.png)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-05-26 02:46 UTC, shinya commented
@maianhtu010596 
PRありがとうございます。
本体のMain Branch（4.2）のコミットが進んでいるので同期取りますね。

2023-05-31 02:51 UTC, chihiro-adachi requested changes

2023-05-31 02:51 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Order/EditController.php
> +    protected function getTaxDisplayType($OrderItemType)
TaxProcessorのコードと重複しているので、うまいこと統一できるとよいなと思いました
https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php#L158

2023-05-31 06:44 UTC, kiy0taka requested changes

2023-05-31 06:44 UTC, kiy0taka commented on src/Eccube/Controller/Admin/Order/EditController.php
> +    protected function getTaxDisplayType($OrderItemType)
OrderHelperあたりにメソッド作っていいと思います。

2023-07-13 09:27 UTC, shinya commented
@maianhtu010596 
上記のレビュー指摘内容について、対応お願いできますでしょうか。
よろしくお願いいたします。

2023-07-19 07:38 UTC, shinya commented
@chihiro-adachi @kiy0taka 
OrderHelperへのメソッドの移動、それに伴うテストの追加を行いました。
確認をお願い致します。

2023-07-19 08:09 UTC, chihiro-adachi requested changes

2023-07-19 08:09 UTC, chihiro-adachi commented on src/Eccube/Controller/Admin/Order/EditController.php
> +            if($orderItem->getTaxDisplayType() == null){
@shinya 
`if($orderItem->getTaxDisplayType() == null){`
↓
`if ($orderItem->getTaxDisplayType() == null) {`

2023-07-19 08:09 UTC, chihiro-adachi commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +       $this->orderHelper = $orderHelper;
@shinya 
phpstanの指摘修正お願いします。

あと空白ずれてる？

2023-07-19 08:09 UTC, chihiro-adachi commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +                $item->setTaxDisplayType($this->orderHelper->getTaxDisplayType($OrderItemType));
@shinya 
phpstanの指摘修正お願いします。

2023-07-19 08:27 UTC, shinya commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +                $item->setTaxDisplayType($this->orderHelper->getTaxDisplayType($OrderItemType));
メンバ変数の宣言が漏れている、という指摘であってますでしょうか？
そちら反映いたしました（認識違いあればおっしゃってください。）

2023-07-19 09:27 UTC, kiy0taka requested changes

2023-07-19 09:27 UTC, kiy0taka commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> -    protected function getTaxDisplayType($OrderItemType)
protectedなメソッドなので削除すると互換性が損なわれます。メソッド自体は残しておいて処理はOrderHelperに移譲する形でお願いします。

2023-07-19 09:35 UTC, shinya commented on src/Eccube/Controller/Admin/Order/EditController.php
> +            if($orderItem->getTaxDisplayType() == null){
修正しました

2023-07-19 09:35 UTC, shinya commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +       $this->orderHelper = $orderHelper;
ズレ直しておきました

2023-07-19 09:35 UTC, shinya commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> -    protected function getTaxDisplayType($OrderItemType)
ありがとうございます。復帰させておきました。

2023-07-20 01:03 UTC, chihiro-adachi requested changes

2023-07-20 01:03 UTC, chihiro-adachi commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +     * @return TaxType
TaxType -> TaxDisplayType

2023-07-20 01:03 UTC, chihiro-adachi commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +        if ($OrderItemType instanceof OrderItemType) {
処理内容はそのまま記述するのではなく、orderHelperに移譲してください。
```
return $this->orderHelper->getTaxDisplayType($OrderItemType)
```

2023-07-20 01:03 UTC, chihiro-adachi commented on src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
> +     *
deprecatedのアノテーションを追加お願いします。
以下のように記載いただければ。

`@deprecated OrderHelper::getTaxDisplayTypeを使用してください`

2023-07-20 01:33 UTC, chihiro-adachi approved these changes

2023-07-20 02:59 UTC, kiy0taka approved these changes

2023-07-20 05:49 UTC, merged