スピナーがボタン内に見えないくなる 不具合の修正
EC-CUBE/ec-cube pull request #5762
Opened 2022-09-01 11:23 UTC by maianhtu010596

## 概要(Overview・Refs Issue)

以下のissueの対応です。
https://github.com/EC-CUBE/ec-cube/issues/5757 スピナーがボタン内に見えない

問題を修正した後の結果は次のようになります。
![image](https://user-images.githubusercontent.com/105194449/187902198-a062a039-45d1-4f6d-a6a7-012196cb5b45.png)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-09-01 23:01 UTC, chihiro-adachi requested changes

2022-09-01 23:01 UTC, chihiro-adachi commented on html/template/admin/assets/js/function.js
> +    $('.btn-ec-regular').attr('data-spinner-color', '#595959');
@maianhtu010596 
`button[type=submit]`に限定して適用お願いします。

2022-09-06 02:34 UTC, maianhtu010596 commented on html/template/admin/assets/js/function.js
> +    $('.btn-ec-regular').attr('data-spinner-color', '#595959');
@chihiro-adachi 変更点を更新し、再度確認しました。この有益なコメントをありがとう。

2022-09-06 11:20 UTC, chihiro-adachi commented
@maianhtu010596 
ありがとうございます。修正確認しました。

2022-09-06 11:20 UTC, chihiro-adachi approved these changes

2022-09-06 11:20 UTC, merged