[4.2] インストーラでのプラグイン有効化/無効化時にキャッシュ削除が失敗する場合があるのを修正
EC-CUBE/ec-cube pull request #5764
Opened 2022-09-02 07:59 UTC by nanasess

## 概要(Overview・Refs Issue)

fixes #5498 
インストーラでのプラグイン有効化/無効化時にキャッシュ削除が失敗する場合があるのを修正

## 方針(Policy)

`KernelEvents::TERMINATE` でキャッシュファイルを強制的に物理削除する

## 実装に関する補足(Appendix)

## テスト（Test)

#5498 の再現手順の事象が再現しなくなるのを確認

## 相談（Discussion）

インストーラのE2Eテストが Step2 までしか無い...

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-09-02 09:33 UTC, chihiro-adachi commented
> インストーラのE2Eテストが Step2 までしか無い...

なんと

2022-09-05 00:17 UTC, chihiro-adachi requested changes

2022-09-05 00:17 UTC, chihiro-adachi commented on src/Eccube/Controller/InstallPluginController.php
> +    public static function getSubscribedEvents()
@nanasess 
このコントローラでの局所的な処理だと思うので、eventListenerで処理したほうがよいかなと思いました。

以下のような記述になります。
https://github.com/EC-CUBE/ProductImagesUploader/blob/4.2/Controller/Admin/ConfigController.php#L50

2022-09-05 01:30 UTC, nanasess commented on src/Eccube/Controller/InstallPluginController.php
> +    public static function getSubscribedEvents()
修正してみました

2022-09-05 23:17 UTC, chihiro-adachi commented
@nanasess 
ご対応ありがとうございます。

有効化/無効化を複数回繰り返し、システムエラーは発生しませんでした。

2022-09-05 23:17 UTC, merged