モーダル内にログイン画面が現れるくなる 不具合の修正
EC-CUBE/ec-cube pull request #5784
Opened 2022-09-12 09:07 UTC by maianhtu010596

## 概要(Overview・Refs Issue)

以下のissueの対応です。
[https://github.com/EC-CUBE/ec-cube/issues/5756](https://github.com/EC-CUBE/ec-cube/issues/5756) モーダル内にログイン画面が現れる

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

この問題を修正し、次のような機能テストを行いました。

- 並び替えに問題がある場合でもエラー表示を追加しました。
![image](https://user-images.githubusercontent.com/105194449/189615470-72d30886-e2b2-4169-8f7b-d313e68236b1.png)

- データの検索に問題がある場合でもエラー表示を追加しました。
![image](https://user-images.githubusercontent.com/105194449/189615051-88ce9f27-3c08-454a-9077-6275597fe83c.png)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-09-16 07:22 UTC, carkn commented
@maianhtu010596 @chihiro-adachi 
ありがとうございます。動作を確認しました。
問題ないかと思います。

2022-09-20 05:15 UTC, chihiro-adachi requested changes

2022-09-20 05:15 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Order/edit.twig
> -            // ページング処理
この部分を削除しているのは意図はありあますか？
@maianhtu010596

2022-09-20 05:15 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.common.failed_to_load: の読み込みに失敗しました
`の`は不要です。

`の読み込みに失敗しました` -> `読み込みに失敗しました`

@maianhtu010596

2022-09-20 09:19 UTC, maianhtu010596 commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.common.failed_to_load: の読み込みに失敗しました
@chihiro-adachi 
コメントありがとうございます。コンテンツが更新されました。ご確認ください。

2022-09-20 09:33 UTC, maianhtu010596 commented on src/Eccube/Resource/template/admin/Order/edit.twig
> -            // ページング処理
@chihiro-adachi 
フィードバックをお寄せいただきありがとうございます。修正コードを再確認して更新しました。

テスト後の結果:
- セッションを削除して現在のページをクリックしたら。
![image](https://user-images.githubusercontent.com/105194449/191221192-99577d42-7df6-4ce4-a608-32d51480e07b.png)

![image](https://user-images.githubusercontent.com/105194449/191222147-9965c3d6-97a4-4628-be8e-f6195ba0128c.png)

- セッションを削除して別のページにアクセスしたら。
![image](https://user-images.githubusercontent.com/105194449/191221525-14c2eedb-53ea-43a6-81ed-0d109b7acb29.png)

![image](https://user-images.githubusercontent.com/105194449/191222185-1730c823-1448-4318-b1f7-25fe585133c7.png)

2023-05-17 10:17 UTC, kiy0taka commented
セッションタイムアウト時にログイン画面にリダイレクトされるのが問題だと思います。
サーバー側でAjaxの場合はリダイレクトではなく401を返すようにすれば、既存の`fail()` が実行されるので各画面のTwigを変更しなくて良くなります。(エラーメッセージは変更してもいいと思いますが)
`AuthenticationEntryPointInterface` を使えばAjaxの場合はログイン画面にリダイレクトしないようにできるかと思います。
https://symfony.com/doc/5.4/security/access_denied_handler.html

2024-02-07 07:56 UTC, dotani1111 commented
@maianhtu010596 
以下のコメントの実装方法を検討するため、クローズさせて頂きます。
https://github.com/EC-CUBE/ec-cube/pull/5784#issuecomment-1551127191

2024-02-07 07:56 UTC, closed without merging