フロント画面へのIPアクセス制限の実装
EC-CUBE/ec-cube pull request #5858
Opened 2022-11-09 08:28 UTC by shinya

## 概要(Overview・Refs Issue)

下記のIssueで取り上げられていた、フロント画面へのIPアクセス制御を実装。
https://github.com/EC-CUBE/ec-cube/issues/5779

## 方針(Policy)

従来から実装されていた、管理画面へのアクセス制限を踏襲し実装。

## 実装に関する補足(Appendix)

管理画面へのアクセス制限を踏襲したものの、
複数の範囲の制限が需要として考えられることから
サブネットマスクでの管理を可能としている点が少し実装ロジックが異なります。
（管理画面ではビットマスクによる指定ができる）

例: 192.168.56.1/32

## テスト（Test)

今から実装予定（テストコード後ほど更新します）

## 相談（Discussion）

EC-CUBEの仕様に乗っ取れているか。
実装箇所が間違っていないか。

## マイナーバージョン互換性保持のための制限事項チェックリスト

※以下、確認中です
- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-11-09 23:04 UTC, chihiro-adachi requested changes

2022-11-09 23:04 UTC, chihiro-adachi commented on src/Eccube/EventListener/IpAddrListener.php
> +    private function checkIpAddrRange($remoteIp, $ipRange)
@shinya 
これつかえそうです。
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/IpUtils.php

2022-11-09 23:04 UTC, chihiro-adachi commented on src/Eccube/Form/Type/Admin/SecurityType.php
> +    private function hasErrorIpAddressAndBitMask($ip)
@shinya 
これつかえそうです。
https://symfony.com/doc/5.4/reference/constraints/Cidr.html

2022-11-16 08:45 UTC, shinya commented on src/Eccube/EventListener/IpAddrListener.php
> +    private function checkIpAddrRange($remoteIp, $ipRange)
変更しました（作成したfunction不要になったので消しました）

2022-11-16 08:45 UTC, shinya commented on src/Eccube/Form/Type/Admin/SecurityType.php
> +    private function hasErrorIpAddressAndBitMask($ip)
こちらも反映しました（functionも消しました）

2022-11-17 00:25 UTC, chihiro-adachi requested changes

2022-11-17 00:25 UTC, chihiro-adachi commented on src/Eccube/EventListener/IpAddrListener.php
> +            foreach ($allowFrontHosts as $host) {
@shinya 
`IpUtils::checkIp($event->getRequest()->getClientIp(), $allowFrontHosts)`
でいけるかと思います。

2022-11-17 00:25 UTC, chihiro-adachi commented on src/Eccube/EventListener/IpAddrListener.php
> +            foreach ($denyFrontHosts as $host) {
@shinya
IpUtils::checkIp($event->getRequest()->getClientIp(), $denyFrontHosts)
でいけるかと思います。

2022-11-17 00:25 UTC, chihiro-adachi commented on src/Eccube/EventListener/IpAddrListener.php
> +        foreach ($allowAdminHosts as $host) {
同上

2022-11-17 00:25 UTC, chihiro-adachi commented on src/Eccube/EventListener/IpAddrListener.php
> +        foreach ($denyAdminHosts as $host) {
同上

2022-11-17 00:25 UTC, chihiro-adachi commented on src/Eccube/Form/Type/Admin/SecurityType.php
> +                            new Assert\Ip(),
ビットマスク通ります？

2022-11-17 00:25 UTC, chihiro-adachi commented on src/Eccube/Form/Type/Admin/SecurityType.php
> +                            new Assert\Ip(),
同上

2022-11-17 00:25 UTC, chihiro-adachi commented on tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
> +
ビットマスク対応しているので、管理画面側の入力もテスト追加お願いします。

2022-11-17 01:27 UTC, shinya commented on src/Eccube/Form/Type/Admin/SecurityType.php
> +                            new Assert\Ip(),
はい。テストは通りました。
AtLeastOneOfでIPとCidrを指定しているので、どちらかのバリデーションをクリアしたらOKになります。

2022-11-17 01:27 UTC, shinya commented on src/Eccube/Form/Type/Admin/SecurityType.php
> +                            new Assert\Ip(),
こちらも上記と同じです

2022-11-17 01:27 UTC, shinya commented on src/Eccube/EventListener/IpAddrListener.php
> +            foreach ($allowFrontHosts as $host) {
確かに・・・！直します

2022-11-17 02:08 UTC, shinya commented on src/Eccube/EventListener/IpAddrListener.php
> +            foreach ($allowFrontHosts as $host) {
こちら配列だとうまく動作しなかったので、このままで行きます

2022-11-17 02:08 UTC, shinya commented on src/Eccube/EventListener/IpAddrListener.php
> +            foreach ($denyFrontHosts as $host) {
同上のため、そのままにします

2022-11-17 02:09 UTC, shinya commented on src/Eccube/EventListener/IpAddrListener.php
> +        foreach ($allowAdminHosts as $host) {
同上のため、そのままにします

2022-11-17 02:09 UTC, shinya commented on src/Eccube/EventListener/IpAddrListener.php
> +        foreach ($denyAdminHosts as $host) {
うまく動作しなかったので、このままで行きます

2022-11-17 02:37 UTC, shinya commented on tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
> +
こちら反映しました

2022-11-28 00:33 UTC, chihiro-adachi approved these changes

2022-11-28 00:40 UTC, chihiro-adachi commented
@shinya 
E2Eテストも修正お願いします。
https://github.com/EC-CUBE/ec-cube/actions/runs/3545779605/jobs/5954207044

2022-12-01 04:14 UTC, chihiro-adachi requested changes

2022-12-01 04:14 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.setting.system.security_front_ip_limit__card_title: ショップサイトIP制限設定
フロント画面でお願いします。

2022-12-01 04:15 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.setting.system.security_front_ip_limit__card_title: ショップサイトIP制限設定
他に`ショップサイト`の文言になっている箇所も、`フロント画面`で統一お願いします。

2022-12-01 09:48 UTC, shinya commented on src/Eccube/Resource/locale/messages.ja.yaml
> +admin.setting.system.security_front_ip_limit__card_title: ショップサイトIP制限設定
承知です！すみません、勘違いしておりました。修正します。

2022-12-05 06:15 UTC, chihiro-adachi approved these changes

2022-12-06 00:25 UTC, chihiro-adachi commented
@shinya 
ありがとうございます。マージしました。

2022-12-07 04:41 UTC, merged