管理画面の会員の注文履歴にページネーションを追加
EC-CUBE/ec-cube pull request #5870
Opened 2022-11-21 00:00 UTC by takeuji

## 概要(Overview・Refs Issue)

管理画面の会員の注文履歴画面にページネーションを追加しました。
(定期購入など、会員あたりの注文件数が多い場合を想定)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

ページネーションの表示件数コンボのテストを追加しました。

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-11-30 06:56 UTC, chihiro-adachi requested changes

2022-11-30 06:56 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/pager.twig
> +                <a class="page-link" h
href?

2022-11-30 07:49 UTC, chihiro-adachi commented
@takeuji 
ページングが表示されている状態で、会員編集の登録ボタンをクリックすると登録処理が実行されないようです。
ご確認いただけますでしょうか。

https://user-images.githubusercontent.com/8196725/204737556-78c6dda7-edb9-4642-abdd-f4fcd4571f16.mov

2022-12-18 23:33 UTC, takeuji commented
@chihiro-adachi ご指摘ありがとうございます。ソースとプルリクのコメントを修正しました。

2023-01-12 02:42 UTC, chihiro-adachi commented
@takeuji 
ありがとうございます、動作問題ないかと思います。

2023-01-12 02:44 UTC, chihiro-adachi commented
@takeuji 
> [ドキュメント](https://github.com/EC-CUBE/eccube-specification/blob/4.2/IntegrationTest/EA05_Customer_%E7%B5%90%E5%90%88%E8%A9%A6%E9%A8%93%E9%A0%85%E7%9B%AE%E6%9B%B8.md)は触っていませんが、会員編集のテスト項目を追加しました。

ドキュメントへもテスト項目追加いただくことはできますでしょうか？

2023-01-12 04:28 UTC, merged