トップページへのリンクをurl関数ではなくbase_pathを使った方法へ変更
EC-CUBE/ec-cube pull request #5883
Opened 2022-12-01 09:37 UTC by shinya

## 概要(Overview・Refs Issue)
#5747 の対応。Untrustedhost時のトップページリンク生成ロジックを変更。
localhostにならないよう自ドメインのトップページへ遷移させる

## 方針(Policy)
url関数を使わずtwigの関数である、app.request.base_pathへ変更

## 実装に関する補足(Appendix)
`app.request.base_path ?? '/'` は、
`app.request.base_path ? app.request.base_path : '/'` と同じです。

## テスト（Test)
UIの簡単な確認で済むため、UTの追加等はしていません。

## 相談（Discussion）
「こういうサイトのURLパターンだとうまく機能しない」というような
考慮漏れがないかどうかを気にしているので見ていただきたい。

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2022-12-01 09:38 UTC, shinya commented
#5747 に関する変更のため、以前issue/prを登録いただいていた @takeuji さんにもご確認いただきたいです。

2022-12-02 00:52 UTC, nanasess requested changes

2022-12-02 00:52 UTC, nanasess commented on src/Eccube/Resource/template/default/error.twig
> +                <a class="ec-blockBtn--cancel" href="{{ app.request.base_path ?? '/' }}">{{ 'common.go_to_top'|trans }}</a>
以下の修正でも良い気がしますが、いかがでしょうか?

```suggestion
                <a class="ec-blockBtn--cancel" href="{{ path('homepage') }}">{{ 'common.go_to_top'|trans }}</a>
```

`/` を使用すると、EC-CUBE をサブディレクトリにインストールした場合に上位階層へのリンクとなってしまう気がします
(既に思慮済みでしたらすみません🙇‍♂️)

2022-12-06 01:28 UTC, shinya commented on src/Eccube/Resource/template/default/error.twig
> +                <a class="ec-blockBtn--cancel" href="{{ app.request.base_path ?? '/' }}">{{ 'common.go_to_top'|trans }}</a>
こちら、サブディレクトリに対応できていなかったので、実装方法を変更いたしました。
ご指摘ありがとうございます。

2022-12-06 01:42 UTC, nanasess approved these changes

2022-12-06 01:45 UTC, nanasess commented
@shinya 
本エラー画面を描画するタイミングは、ルーティングが設定される前で `path()` 関数が使用できないため、 `app.request.base_path` を使用している感じですね！

2022-12-07 04:44 UTC, chihiro-adachi commented
@nanasess 
確認ありがとうございます。

@shinya 
動作確認しました。サブディレクトリでも問題ありません。

2022-12-07 04:45 UTC, merged