EC-CUBEの基本設定内にあるメールの設定を修正したい #5937
EC-CUBE/ec-cube pull request #5938
Opened 2023-02-10 00:13 UTC by cajiya-nakamura

## 概要(Overview・Refs Issue)

EC-CUBEの基本設定内にあるメールの設定を修正したい #5937
の対応です。

仮会員登録再送メールのfromを Email03からEmail01に変更
パスワード再発行メールのbccに Email01 を設定

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-03-13 07:25 UTC, chihiro-adachi commented
@cajiya-nakamura 
ラベルの変更に関しても問題ないかと思いますので、追加で修正いただければと思います。
https://github.com/EC-CUBE/ec-cube/issues/5937#issuecomment-1449442147

2023-03-23 01:30 UTC, cajiya-nakamura commented
@chihiro-adachi 
ラベル名と並び順、変更してコミットしましたmm

2023-03-27 05:20 UTC, chihiro-adachi requested changes

2023-03-27 05:20 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
> +                                    <div class="d-inline-block" class="d-inline-block" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ 'tooltip.setting.shop.shop.email_reply_to'|trans }}">
@cajiya-nakamura 
class="d-inline-block"が重複しているようです。

2023-03-27 05:21 UTC, chihiro-adachi commented
@cajiya-nakamura 
ありがとうございます。一箇所だけコメントしましたのでご確認ください。

2023-03-29 02:42 UTC, cajiya-nakamura commented
@chihiro-adachi 
`.d-inline-block` の重複、修正しましたmm

2023-04-03 04:19 UTC, merged

2023-04-03 04:19 UTC, chihiro-adachi commented
@cajiya-nakamura 
ありがとうございます。マージしました。