feat:管理画面>商品一覧画面の「登録日」「更新日」検索へのバリデーション
EC-CUBE/ec-cube pull request #5951
Opened 2023-02-20 02:28 UTC by dotani1111

## 概要(Overview・Refs Issue)

商品一覧画面の「登録日」、「更新日」検索について
https://github.com/EC-CUBE/ec-cube/issues/5712

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

![image](https://user-images.githubusercontent.com/121000728/219995308-63ee60c4-2256-487b-870e-98db0873cf97.png)

## 相談（Discussion）

・エラーを２つのフォームに表示しているが、１つのほうが良いか
・エラーメッセージの内容が適当か
・実装箇所が適当か

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-03-22 06:51 UTC, chihiro-adachi commented
@dotani1111 
終了日時のエラーとし、終了日時にのみメッセージを表示するようにしましょう。
また、受注一覧や会員一覧の類似箇所へも実装お願いします。

2023-04-03 06:00 UTC, dotani1111 commented
@chihiro-adachi 
終了日時のみに修正、その他項目についてもバリデーションを追加致しました。

2023-04-12 07:13 UTC, chihiro-adachi requested changes

2023-04-12 07:13 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.en.yaml
> +admin.product.date_range_error: End date is set after start date
@dotani1111 
会員や受注でも利用するメッセージなので、`admin.product`ではなく`admin.common`を使ってください。

2023-04-12 07:59 UTC, chihiro-adachi commented on src/Eccube/Resource/locale/messages.en.yaml
> +admin.product.date_range_error: End date is set after start date
jaも同様でお願いします

2023-04-17 02:42 UTC, dotani1111 commented on src/Eccube/Resource/locale/messages.en.yaml
> +admin.product.date_range_error: End date is set after start date
@chihiro-adachi 
修正致しました。

2023-12-11 05:28 UTC, shinya commented
検証して問題なければ、次回のVersionUPでの取り込み予定とします。

2024-01-24 07:38 UTC, chihiro-adachi approved these changes

2024-02-07 07:30 UTC, shinya approved these changes

2024-02-07 07:32 UTC, merged