fontawesomeにintegrity追加
EC-CUBE/ec-cube pull request #5969
Opened 2023-03-25 02:42 UTC by Atsu0601

## 概要(Overview・Refs Issue)

下記の2ファイルにfontawesomeにintegrity追加しました。
/src/Eccube/Resource/template/admin/default_frame.twig
src/Eccube/Resource/template/admin/error.twig
Issue:#5946

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-03-27 05:12 UTC, chihiro-adachi commented
@Atsu0601 
ありがとうございます。以下エラーがでていますのでご確認お願いできますでしょうか。
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/8196725/227846568-ba7830f7-098a-46e3-bdb1-fe0460aade0f.png">

2023-03-27 08:06 UTC, Atsu0601 commented
@chihiro-adachi 
ご確認ありがとうございます。
私のローカル環境では確認できなかったのですが、`crossOrigin='anonymous'` の記述を追加しようと思います。

先ほどコミットしたので、ご確認お願いできますでしょうか。
お手数ですが、宜しくお願い致します。

2023-04-03 04:22 UTC, chihiro-adachi requested changes

2023-04-03 04:22 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/default_frame.twig
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymo
`crossOrigin` -> `crossorigin`でお願いします。

2023-04-03 04:22 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/default_frame.twig
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymo
v4-shims.cssのハッシュ値はall.cssと同じ値ですが問題ないでしょうか？

2023-04-05 16:17 UTC, Atsu0601 commented on src/Eccube/Resource/template/admin/default_frame.twig
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymo
ハッシュ値は再度計算したものに差し替えいたします。

2023-04-05 16:17 UTC, Atsu0601 commented on src/Eccube/Resource/template/admin/default_frame.twig
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymo
こちらも変更致します。ありがとうございます。

2023-04-13 01:45 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/default_frame.twig
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymo
@Atsu0601 
all.cssのハッシュ値は合っていると思われますので、v4-shims.cssの方を変更お願いできますでしょうか。

2023-04-13 01:50 UTC, chihiro-adachi commented on src/Eccube/Resource/template/admin/default_frame.twig
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymo
またハッシュ値の生成は以下を参考にしていただければと思います。
https://developer.mozilla.org/ja/docs/Web/Security/Subresource_Integrity#sri_%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B%E3%83%84%E3%83%BC%E3%83%AB

2023-04-17 05:58 UTC, chihiro-adachi commented
@Atsu0601 
以下でお願いできますでしょうか。
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css" integrity="sha384-lmquXrF9qn7mMo6iRQ662vN44vTTVUBpcdtDFWPxD9uFPqC/aMn6pcQrTTupiv1A" crossorigin="anonymous">
```

2023-05-15 05:17 UTC, shinya commented
@Atsu0601 
4.2（現メインブランチ）の最新を取り込み直していただくことで、おそらく落ちているテストが通る見込みです。
お手数ですがご対応をお願いします。

2023-05-22 09:00 UTC, shinya commented
@Atsu0601 
最新の取り込み対応ありがとうございます！

@kiy0taka @chihiro-adachi 
GitHubActionsのテスト落ちていますが、ローカルの実行では問題なく成功しています。
（ソースコードの差分からも影響はないと判断できるかと思います）
こちらマージの対応に入りたく。最終レビュー頂けませんでしょうか

2023-05-22 09:17 UTC, kiy0taka requested changes

2023-05-22 09:17 UTC, kiy0taka commented on .gitignore
> +/html_bundle/*
この修正は不要なものかと思われますので、コミットごと削除お願いします。

2023-05-22 09:25 UTC, shinya commented on .gitignore
> +/html_bundle/*
@kiy0taka 
ありがとうございます。見落としていました。

@Atsu0601 
すみませんが上記の通り、[こちらのコミット](https://github.com/EC-CUBE/ec-cube/pull/5969/commits/a148e035d049e1291e4df8fc8174674511d2b4eb)のご対応をお願い致します。
gitignoreの変更は今回のこの修正には関係の無いものとの認識です。
（もっと早くに気づけず失礼いたしました）

2023-05-24 06:37 UTC, shinya commented on .gitignore
> +/html_bundle/*
こちら私の方でrevertしておきます

2023-05-24 06:41 UTC, shinya commented
@kiy0taka 
こちら該当のgitignoreの修正戻しておきました。
再レビューお願いいたします。

2023-05-24 08:01 UTC, kiy0taka approved these changes

2023-05-24 08:08 UTC, chihiro-adachi approved these changes

2023-05-25 00:36 UTC, shinya commented
お二人共レビューありがとうございます。
マージします。

2023-05-25 00:37 UTC, merged