feat:会員による重要操作時のメール通知機能
EC-CUBE/ec-cube pull request #5989
Opened 2023-05-16 02:26 UTC by dotani1111

## 概要(Overview・Refs Issue)

https://github.com/EC-CUBE/ec-cube/issues/5373

## 方針(Policy)

 メールが飛ぶ場合
 - 会員情報の編集
 - 会員お届け先の登録・編集・削除

## 実装に関する補足(Appendix)

## テスト（Test)

会員情報の変更、お届け先の登録・変更・削除にて、メールが飛ぶことを確認
例：会員情報の変更時メール
<img width="943" alt="image" src="https://github.com/EC-CUBE/ec-cube/assets/121000728/69f3889e-9b79-494c-b462-fdbaa8fbed59">

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更はありません
- [x] フックポイントの呼び出しタイミングの変更はありません
- [x] フックポイントのパラメータの削除・データ型の変更はありません
- [x] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [x] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-05-30 07:27 UTC, shinya commented on src/Eccube/Service/MailService.php
> +        $ipAddress = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['SERVER_SOFTWARE'] : '0.0.0.0' ;
これだと永遠にIPアドレス使われないってことにならないでしょうか？
両方ともREMOTE_ADDRで良い気がします

2023-05-30 08:14 UTC, dotani1111 commented on src/Eccube/Service/MailService.php
> +        $ipAddress = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['SERVER_SOFTWARE'] : '0.0.0.0' ;
すみません、「両方とも」とはどういう意味でしょうか？
セットされていない場合はエラーになりますが、平気でしょうか？（例えば、テストの場合など）

2023-05-30 08:33 UTC, shinya commented on src/Eccube/Service/MailService.php
> +        $ipAddress = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['SERVER_SOFTWARE'] : '0.0.0.0' ;
説明不足ですみません。
issetで「REMOTE_ADDR」の存在チェックをしているのにも関わらず、代入するのは「SERVER_SOFTWARE」を採用しているのが気になりました。これは「SERVER_SOFTWARE」の部分も「REMOTE_ADDR」で良い気がする、という意味で両方という表現を使いました。

2023-05-31 02:35 UTC, chihiro-adachi requested changes, later dismissed

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Service/MailService.php
> +        $ipAddress = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '0.0.0.0' ;
`$request->getClientIp()`でIPアドレス取得できます。
※$_SERVERなどPHPのグローバル変数を直接使うのは避けてください。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Service/MailService.php
> +    public function sendEventNotifyMail(Customer $Customer, Request $Request, $eventName)
UnitTest作成お願いします。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Service/MailService.php
> +        $htmlFileName = $this->getHtmlTemplate($MailTemplate->getFileName());
@dotani1111 
HTMLメールテンプレートを作成していないのは意図したものですか？

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Mail/event_notify.twig
> +日時：{{ date()|date('Y年m月d日 H時i分s秒') }}
`date_sec`を使ってください

2023-05-31 02:35 UTC, chihiro-adachi commented on app/DoctrineMigrations/Version20230515023836.php
> +        $id = $this->connection->fetchOne('SELECT MAX(id) + 1 FROM dtb_mail_template');
pgsqlの場合はシーケンス更新も必要かなと思います。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Controller/Mypage/ChangeController.php
> +        $this->BaseInfo = $baseInfoRepository->get();
コンストラクタ内でメソッド呼び出すのはできるだけ避けてほしいです
※lazy load効かなくなるので。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Service/MailService.php
> +        $preEmail = $Request->get('preEmail');
request->getで値を引き渡すのはセキュリティ上望ましくないので避けてください。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Service/MailService.php
> +    public function sendEventNotifyMail(Customer $Customer, Request $Request, $eventName)
ServiceクラスがRequestに依存するのは避けたほうが無難です
※テスト書きにくい、バッチ実行時に動作しないなど。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Service/MailService.php
> +        $htmlFileName = $this->getHtmlTemplate($MailTemplate->getFileName());
※意図したものであればPRやIssueに記載お願いします。

2023-05-31 02:35 UTC, chihiro-adachi commented on src/Eccube/Resource/template/default/Mypage/change.twig
> +                                        <input type="hidden" name="preEmail" value="{{ preEmail }}">
変更前のメールアドレスをhiddenで引き回す必要ありますか？

2023-05-31 02:39 UTC, chihiro-adachi commented
E2Eテストも追加・更新(あれば)お願いします。

2023-05-31 06:42 UTC, kiy0taka requested changes

2023-05-31 06:42 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/DeliveryController.php
> +            $this->mailService->sendEventNotifyMail($Customer, $request, trans('front.mypage.delivery.notify_title'));
ここでも `isOptionMailNotifier()`チェックが必要だと思います。

2023-05-31 06:42 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/DeliveryController.php
> +        $this->mailService->sendEventNotifyMail($Customer, $request, trans('front.mypage.delivery.notify_title'));
こちらも。

2023-05-31 06:42 UTC, kiy0taka commented on src/Eccube/Resource/doctrine/import_csv/en/dtb_mail_template.csv
> +9,,Notification email,Mail/event_notify.twig,[eventName] notification,2017-03-07 10:14:52,2017-03-07 10:14:52,mailtemplate
`[eventName] notification` になっています。

2023-05-31 06:42 UTC, kiy0taka commented on app/DoctrineMigrations/Version20230515023836.php
> +        $id = $this->connection->fetchOne('SELECT MAX(id) + 1 FROM dtb_mail_template');
idを指定しなければ自動裁判してくれると思います。

2023-05-31 06:42 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Mypage/change.twig
> +                                        <input type="hidden" name="preEmail" value="{{ preEmail }}">
改ざんされるのでよろしくないですね。

2023-05-31 06:42 UTC, kiy0taka commented on src/Eccube/Service/MailService.php
> +        $ipAddress = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '0.0.0.0' ;
リバースプロキシ等があると期待するIPアドレスを取れないです。
https://symfony.com/doc/5.4/create_framework/http_foundation.html

2023-05-31 06:42 UTC, kiy0taka commented on src/Eccube/Service/MailService.php
> +        $tpl_name = 'Mail/event_notify.twig';
メソッド名とかもそうですが、`event_notify` というのが漠然としすぎなので、`customer_change_notify` とか具体的なものにお願いします。

2023-06-02 05:31 UTC, kiy0taka requested changes
`shopping_shipping_edit` と `shopping_shipping_multiple_edit` でもお届先情報を編集できるので重要操作メール通知が必要でした。

2023-06-02 05:31 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/ChangeController.php
> +        var_dump($preEmail);
`var_dump`を削除してください

2023-06-02 05:31 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/ChangeController.php
> +                $userDate['userAgent'] = $request->headers->get('User-Agent');
`userData`のtypo?

2023-06-02 05:31 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/ChangeController.php
> +use Symfony\Component\Form\Form;
使っていないと思うので削除しておいてください。

2023-06-02 05:31 UTC, kiy0taka commented on app/DoctrineMigrations/Version20230515023836.php
> +        $this->addSql("
`Mail/customer_change_notify.twig` がすでに登録されていないかのチェックお願いします。

2023-06-02 05:31 UTC, kiy0taka commented on tests/Eccube/Tests/Service/MailServiceTest.php
> +    public function testCustomerChangeNotifyMail01()
メソッド名は連番ではなく、意味のあるものにしてください。

2023-06-02 05:31 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
> +{#
テキストメールと内容に少し差があるのでどちらかに統一お願いします。HTMLの方には以下の文言がふくまれていないようです。
- 「※本メールは自動配信メールです。」
- 「もしお心当たりが無い場合は...」

2023-06-02 05:36 UTC, kiy0taka requested changes

2023-06-02 05:36 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/DeliveryController.php
> +                $userDate['preEmail'] = $request->getSession()->get('preEmail');
ここで `preEmail`は不要だと思います。

2023-06-02 05:36 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/DeliveryController.php
> +            $userDate['preEmail'] = $request->getSession()->get('preEmail');
ここで `preEmail`は不要だと思います。

2023-06-02 05:36 UTC, shinya commented on tests/Eccube/Tests/Service/MailServiceTest.php
> +    public function testCustomerChangeNotifyMail01()
こちら私の方で修正直します

2023-06-02 05:37 UTC, shinya commented on src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
> +{#
こちらも私の方で修正します

2023-06-02 05:38 UTC, kiy0taka requested changes

2023-06-02 05:38 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
> +                            日時：{{ date()|date('Y年m月d日 H時i分s秒') }}<br/>
`date_sec`

2023-06-02 05:41 UTC, kiy0taka requested changes

2023-06-02 05:41 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/ChangeController.php
> +        $this->BaseInfo = $baseInfoRepository;
`$this->BaseInfo` ではなく `$this->baseInfoRespository`に変更お願いします。

2023-06-02 06:12 UTC, shinya commented on src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
> +{#
@kiy0taka 
「もしお心当たりが無い場合は...」の部分はメールのフッターにあるので不要だと思っているのですがいかがでしょうか。
<img width="932" alt="スクリーンショット 2023-06-02 15 06 40" src="https://github.com/EC-CUBE/ec-cube/assets/8691817/3e855aeb-f7fe-4622-9829-f01bafab4ea6">

2023-06-02 06:13 UTC, kiy0taka commented on src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
> +{#
@shinya 見落としてました。それで問題ないです。

2023-06-02 06:51 UTC, shinya commented on src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
> +{#
@kiy0taka 
ありがとうございます！ではこの指摘に関しては「※本メールは自動配信メールです。」の適用のみさせていただきます。
（そして反映済みです）

2023-06-02 10:07 UTC, kiy0taka requested changes

2023-06-02 10:07 UTC, kiy0taka commented on src/Eccube/Controller/Mypage/ChangeController.php
> +    protected  $baseInfoRepository;
不要なスペースが入ってます。

2023-06-02 10:07 UTC, kiy0taka commented on src/Eccube/Controller/ShippingMultipleController.php
> +                    $Customer = $this->getUser();
すでに`$Customer`があるので不要です。

2023-06-02 10:07 UTC, kiy0taka commented on src/Eccube/Controller/ShoppingController.php
> +                $this->mailService->sendCustomerChangeNotifyMail($Customer, $userData, trans('front.mypage.delivery.notify_title'));
ゲスト購入時にエラーになります。

2023-06-02 10:07 UTC, kiy0taka commented on tests/Eccube/Tests/Service/MailServiceTest.php
> +            'preEmail' => $this->Customer->getEmail(),
このケースでは `preEmail` は渡ってこなくなりました。

2023-06-02 11:25 UTC, kiy0taka approved these changes

2023-06-05 06:55 UTC, merged