feat:会員情報編集・お届け先編集時にスロットリングを追加
EC-CUBE/ec-cube pull request #5998
Opened 2023-05-29 06:59 UTC by dotani1111

## 概要(Overview・Refs Issue)

対応するissue : https://github.com/EC-CUBE/ec-cube/issues/5996
以下の操作に対して、スロットリングを追加します。
- マイページ
  - 会員情報編集
- お届け先
  - 追加
  - 編集
  - 削除

## 方針(Policy)

  https://github.com/EC-CUBE/ec-cube/pull/5881
  https://doc4.ec-cube.net/customize_throttling

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更はありません
- [x] フックポイントの呼び出しタイミングの変更はありません
- [x] フックポイントのパラメータの削除・データ型の変更はありません
- [x] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [x] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-05-30 08:25 UTC, chihiro-adachi commented
@dotani1111 
- E2Eテストの追加をお願いします。
- https://doc4.ec-cube.net/customize_throttling も更新お願いします。

2023-05-31 09:04 UTC, kiy0taka requested changes
マイページ以下をIPでスロットリングする意味はないかと思います。

2023-05-31 10:00 UTC, dotani1111 commented
@kiy0taka 
ありがとうございます。
＞マイページ以下をIPでスロットリングする意味はないかと思います。
PO合意しまして、「IPでスロットリングはなしでお願いします。」となりました。

2023-06-02 09:07 UTC, dotani1111 commented
PO合意
shopping以下の配送先追加のルーティングに関して、customerのみで良い

2023-06-02 12:15 UTC, kiy0taka requested changes
[e2e-test-throttling.ym](https://github.com/EC-CUBE/ec-cube/blob/0bf8995109b90934b872634dd9aedabd07ad1131/.github/workflows/e2e-test-throttling.yml#L24) の修正もお願いします。

2023-06-02 12:25 UTC, kiy0taka approved these changes

2023-06-04 23:11 UTC, chihiro-adachi commented
@dotani1111 @shinya 
こちらにも反映お願いできると助かります。
https://github.com/EC-CUBE/eccube-specification/blob/4.2/IntegrationTest/EF09_%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88%E3%83%AA%E3%83%B3%E3%82%B0_%E7%B5%90%E5%90%88%E8%A9%A6%E9%A8%93%E9%A0%85%E7%9B%AE%E6%9B%B8.md

2023-06-05 06:55 UTC, merged