重複して在庫が登録されてしまう問題に対処
EC-CUBE/ec-cube pull request #6029
Opened 2023-08-04 04:06 UTC by shinya

## 概要(Overview・Refs Issue)
#6028 でissueが上がっていた在庫情報が重複して登録されてしまい、
在庫情報がズレてしまう問題に対処。

## 方針(Policy)
バグの対処のみの変更

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [x] 既存機能の仕様変更はありません
- [x] フックポイントの呼び出しタイミングの変更はありません
- [x] フックポイントのパラメータの削除・データ型の変更はありません
- [x] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [x] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [x] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-08-04 04:07 UTC, shinya commented
テスト結果を後ほど追記します。

2023-08-07 05:06 UTC, dotani1111 commented
@shinya 
DBに値が二つ登録されていない事が確認できるような、テストコードを追加お願い致します。

2023-09-21 02:56 UTC, dotani1111 commented
追加したテストが落ちていますね。。

2023-09-26 00:11 UTC, nanasess reviewed
何故この改修で改善できるかを実装の補足へ記載していただくと、後々なぜこんな修正入れたんだっけ？となった時に助かるかと思います

2023-09-26 00:21 UTC, chihiro-adachi requested changes

2023-09-26 00:21 UTC, chihiro-adachi commented on codeception/acceptance/EA03ProductCest.php
> +    public function product_一覧からの規格編集_規格あり_規格操作(AcceptanceTester $I)
テストのメソッド名は、何に対するテストかわかるようにするとよいかと思います。

また、メソッドコメントででissueやprを参照しておくとわかりやすいです。
`@see https://github.com/EC-CUBE/ec-cube/pull/xxx`

2023-09-26 00:21 UTC, chihiro-adachi commented on codeception/acceptance/EA03ProductCest.php
> +    private $conn;
dbal特に使ってなければ削除でお願いします。

2023-09-26 00:21 UTC, chihiro-adachi commented on codeception/acceptance/EA03ProductCest.php
> +        $this->conn = $this->em->getConnection();
dbal特に使ってなければ削除でお願いします。

2023-09-26 00:23 UTC, chihiro-adachi commented
@dotani1111 
テスト仕様書の方にもテスト追加お願いします。
https://github.com/EC-CUBE/eccube-specification/tree/4.2/IntegrationTest

2023-09-27 00:10 UTC, kiy0taka requested changes

2023-09-27 00:10 UTC, kiy0taka commented on codeception/acceptance/EA03ProductCest.php
> +        $I->assertEquals('10', $stock, 'Stockが一致');
在庫のズレが発生した原因は同じ`product_class_id`に対するレコードが複数件できていたのが原因なので、1件しかできていないことと同じ値であることの両方を検証する必要があります。

2023-09-27 02:21 UTC, dotani1111 commented
テスト仕様書に追加しました。
https://github.com/EC-CUBE/eccube-specification/pull/112

2023-09-27 08:26 UTC, dotani1111 commented on codeception/acceptance/EA03ProductCest.php
> +        $this->conn = $this->em->getConnection();
@chihiro-adachi 
ありがとうございます。
こちら使用する方針になりました。

2023-09-27 08:26 UTC, dotani1111 commented on codeception/acceptance/EA03ProductCest.php
> +    private $conn;
@chihiro-adachi 
ありがとうございます。
こちら使用する方針になりました。

2023-09-27 08:26 UTC, dotani1111 commented on codeception/acceptance/EA03ProductCest.php
> +    public function product_一覧からの規格編集_規格あり_規格操作(AcceptanceTester $I)
@chihiro-adachi 
ありがとうございます。
こちら対応いたしました。

2023-09-28 00:05 UTC, dotani1111 commented on codeception/acceptance/EA03ProductCest.php
> +        $I->assertEquals('10', $stock, 'Stockが一致');
@kiy0taka 
こちら対応しました。

2023-09-28 07:50 UTC, kiy0taka requested changes

2023-09-28 07:50 UTC, kiy0taka commented on app/DoctrineMigrations/Version20230928014611.php
> +    public function up(Schema $schema): void
エラーになりました。
```
$ bin/console doctrine:migrations:execute DoctrineMigrations\\Version20230928014611 --no-interaction
[notice] Executing DoctrineMigrations\Version20230928014611 up
[error] Migration DoctrineMigrations\Version20230928014611 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "dtb_product_stock.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:              id,
                     ^"
```

2023-09-28 08:44 UTC, dotani1111 commented on app/DoctrineMigrations/Version20230928014611.php
> +    public function up(Schema $schema): void
@kiy0taka 
すみません、こちら修正いたしました。

2023-09-29 01:47 UTC, kiy0taka requested changes

2023-09-29 01:47 UTC, kiy0taka commented on app/DoctrineMigrations/Version20230928014611.php
> +                $this->addSql("INSERT INTO dtb_product_stock (product_class_id, creator_id, stock, create_date, update_date, discriminator_type) VALUES (:pc_id, NULL, :stock, CURRENT_DATE, CURRENT_DA
時刻も登録したいので`CURRENT_TIMESTAMP`でお願いします。

2023-09-29 02:46 UTC, shinya commented on app/DoctrineMigrations/Version20230928014611.php
> +                $this->addSql("INSERT INTO dtb_product_stock (product_class_id, creator_id, stock, create_date, update_date, discriminator_type) VALUES (:pc_id, NULL, :stock, CURRENT_DATE, CURRENT_DA
@kiy0taka 
こちら改修しました（Postgres・MySQL共に動作確認済み）

2023-09-29 02:57 UTC, kiy0taka approved these changes

2023-09-29 04:48 UTC, ji-eunsoo approved these changes

2023-10-01 23:23 UTC, chihiro-adachi approved these changes

2023-10-02 00:17 UTC, merged