新規会員登録（入力）画面のスロットリング追加
EC-CUBE/ec-cube pull request #6038
Opened 2023-09-15 04:14 UTC by KenTanaka

## 概要(Overview・Refs Issue)
#5279

## 方針(Policy)
- メアド重複のみのスロットリングが実装できない為、新規会員登録（入力）画面のPOSTでスロットリングする
- スロットリング対象はIPのみとする（未ログイン状態である為）

## 実装に関する補足(Appendix)

## テスト（Test)
- 手動での試験実施済み
  - 新規会員登録画面で閾値分の妥当性エラーとなるPOSTを繰り返す
  - 新規会員登録画面 <> 確認画面を往復する
- E2Eテストを追加

## 相談（Discussion）
- メアド重複のみハンドリングしている訳ではない事に留意

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [〇] 既存機能の仕様変更はありません
- [〇] フックポイントの呼び出しタイミングの変更はありません
- [〇] フックポイントのパラメータの削除・データ型の変更はありません
- [〇] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [〇] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [〇] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-09-20 05:09 UTC, chihiro-adachi commented
doc4も更新お願いしてよいでしょうか？
https://doc4.ec-cube.net/customize_throttling

2023-09-20 05:15 UTC, dotani1111 commented
@KenTanaka 
入力画面にてスロットリングが掛かるE2Eテストをお願いします。

2023-09-21 05:46 UTC, KenTanaka commented
@dotani1111 
E2Eの方追加しました。
（EF0901-UC01-T18_会員登録_入力）

2023-09-22 07:41 UTC, dotani1111 commented on app/config/eccube/packages/prod/eccube_rate_limiter.yaml
>          entry:
@KenTanaka 
entrytとentry_completeの意図がわかるようにコメントの追加をお願いします。

2023-09-27 04:12 UTC, ji-eunsoo commented on app/config/eccube/packages/prod/eccube_rate_limiter.yaml
>          entry:
@dotani1111 
ありがとうございます。追加しました。

2023-09-28 01:04 UTC, dotani1111 approved these changes

2023-09-28 01:24 UTC, chihiro-adachi submitted a review, later dismissed

2023-09-28 01:27 UTC, chihiro-adachi commented
マイページの会員編集画面でも同様のスロットリングが必要かと思いましたが、本PRでは対象外でしょうか？

2023-09-28 01:35 UTC, dotani1111 requested changes

2023-09-28 01:35 UTC, dotani1111 commented on codeception/acceptance/EF09ThrottlingCest.php
> +                ->新規会員登録_入力エラー();
@ji-eunsoo 
これだと25回以上（50回でも）テストが成功するので、
失敗した場合、「入力されていません。」を見たら良いかと思います。
`$I->see('入力されていません。','p.ec-errorMessage');`

2023-09-28 02:39 UTC, ji-eunsoo commented
> マイページの会員編集画面でも同様のスロットリングが必要かと思いましたが、本PRでは対象外でしょうか？

@chihiro-adachi 
ありがとうございます。マイページの会員編集画面には既にスロットリングが入っており、対応不要となります。
https://github.com/EC-CUBE/ec-cube/blob/f8095c64fbdd89093401e733d78ee1bfa132085f/app/config/eccube/packages/prod/eccube_rate_limiter.yaml#L17

2023-09-28 03:09 UTC, ji-eunsoo commented
@chihiro-adachi 
25回の入力テストで、p.ec-errorMessageの要素の内容を確認するように修正したため、
お手数をおかしますが、再度のほど、よろしくお願いいたします。

2023-09-28 04:09 UTC, shinya submitted a review, later dismissed

2023-09-28 04:23 UTC, chihiro-adachi commented
> > マイページの会員編集画面でも同様のスロットリングが必要かと思いましたが、本PRでは対象外でしょうか？
> 
> @chihiro-adachi ありがとうございます。マイページの会員編集画面には既にスロットリングが入っており、対応不要となります。
> 
> https://github.com/EC-CUBE/ec-cube/blob/f8095c64fbdd89093401e733d78ee1bfa132085f/app/config/eccube/packages/prod/eccube_rate_limiter.yaml#L17

ありがとうございます。了解です。

2023-09-28 04:23 UTC, chihiro-adachi commented
> @chihiro-adachi 25回の入力テストで、p.ec-errorMessageの要素の内容を確認するように修正したため、 お手数をおかしますが、再度のほど、よろしくお願いいたします。

問題ないです。

2023-09-28 04:54 UTC, kiy0taka commented on codeception/_support/Page/Front/EntryPage.php
> +    public function 新規会員登録_入力エラー($form = [])
このメソッドが`新規会員登録()`とほぼ同じで冗長なコードになっています。
今回のテストではエラーである必要もないと思うので、メソッド`新規会員登録()`をフォーム入力/同意する/会員登録するにそれぞれ分けて利用するようにしましょう。

2023-09-28 08:07 UTC, chihiro-adachi approved these changes, later dismissed

2023-09-29 01:54 UTC, kiy0taka approved these changes

2023-09-29 04:50 UTC, ji-eunsoo approved these changes

2023-09-29 04:50 UTC, ikeike9o9o commented on codeception/acceptance/EF09ThrottlingCest.php
> +                ->新規会員登録_入力エラー();
@dotani1111 
ありがとうございます。追加しました。

2023-09-29 04:50 UTC, ikeike9o9o commented on codeception/_support/Page/Front/EntryPage.php
> +    public function 新規会員登録_入力エラー($form = [])
@kiy0taka 
ありがとうございます。修正いたしました。

2023-09-29 04:50 UTC, shinya approved these changes

2023-09-29 05:06 UTC, nanasess approved these changes

2023-09-29 05:09 UTC, dotani1111 approved these changes

2023-09-29 05:14 UTC, merged