Symfony6対応
EC-CUBE/ec-cube pull request #6073
Opened 2023-12-13 07:33 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

#6069

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-12-25 23:27 UTC, chihiro-adachi commented
TODO
- UTの実行時間が20分以上かかる
- SameSiteCookieの挙動変更
- DoctrineのCache

2024-01-31 06:21 UTC, nanasess requested changes

2024-01-31 06:21 UTC, nanasess commented on src/Eccube/Common/EccubeConfig.php
> +        throw new \Exception();
これが呼ばれるのはプログラミングのミスだと思うので、 LogickException で良いと思います
```suggestion
        throw new \LogicException();
```

2024-01-31 06:21 UTC, nanasess commented on src/Eccube/Security/Core/User/CustomerProvider.php
> +        return $this->loadUserByUsername($identifier);
`loadUserByUsername()` が deprecated なので、`loadUserByIdentifier` に処理を実装して、 loadUserByUsername() の中で loadUserByIdentifier を呼んだ方が良いと思います

2024-01-31 06:21 UTC, nanasess commented on src/Eccube/Security/Core/User/MemberProvider.php
> +        return $this->loadUserByUsername($identifier);
`loadUserByUsername()` が deprecated なので、`loadUserByIdentifier` に処理を実装して、 loadUserByUsername() の中で loadUserByIdentifier を呼んだ方が良いと思います

2024-01-31 06:21 UTC, nanasess commented on src/Eccube/Command/GenerateProxyCommand.php
> +        // TODO doctrine/anntationsをv2へアップデート。影響がある場合は要調査。
ここのコメントが気になります

2024-01-31 06:23 UTC, chihiro-adachi commented on src/Eccube/Common/EccubeConfig.php
> +        throw new \Exception();
ありがとうございます、修正します。

2024-01-31 06:23 UTC, chihiro-adachi commented on src/Eccube/Security/Core/User/CustomerProvider.php
> +        return $this->loadUserByUsername($identifier);
たしかにそうですね。修正します。

2024-01-31 06:23 UTC, chihiro-adachi commented on src/Eccube/Security/Core/User/MemberProvider.php
> +        return $this->loadUserByUsername($identifier);
たしかにそうですね。修正します。

2024-01-31 06:30 UTC, chihiro-adachi commented on src/Eccube/Command/GenerateProxyCommand.php
> +        // TODO doctrine/anntationsをv2へアップデート。影響がある場合は要調査。
@nanasess 
ありがとうございます。
doctrine/anntationsをv2へアップデートした際に後で確認しようと記載したコメントですが

- 以降の修正でgithub actionsも全てパスできた
- 商品レビュープラグインの4.3対応でも、Entity拡張でのテーブル追加等、問題はなさそう

ので、特に影響なしと判断しています。

今では不要なコメントなので削除しておきます。

2024-02-06 01:21 UTC, nanasess approved these changes, later dismissed

2024-02-07 07:06 UTC, dotani1111 commented
2月末ぐらいを目処に、mergeしていきたいと思います。

2024-02-21 07:11 UTC, nanasess approved these changes, later dismissed

2024-02-21 07:11 UTC, dotani1111 submitted a review, later dismissed

2024-02-26 00:51 UTC, dotani1111 approved these changes

2024-02-26 00:52 UTC, shinya approved these changes

2024-02-26 00:53 UTC, nanasess approved these changes
LGTM

2024-02-26 01:08 UTC, ji-eunsoo approved these changes

2024-02-26 01:08 UTC, merged